### ISSUE TITLE
modify dnaPipeTE.py --JM to --max_memory to support new Trinity versions

### ISSUE THREAD

**Issue by estolle** [clemgoub/dnaPipeTE#1]
Hi

The changes from v1 are great! 
I just managed to get it running on a new system and was trying trinity 2.2 (latest).
the dnapipete.py needs to be amended: --max_memory instead of --JM for making it compatible

There seems to be another issue at the Butterfly step
###### 

Butterfly assemblies are written to /dnaPipeTE/testout/Trinity_run1/Trinity.fasta
###### 

Trinity iteration 1 Done'
Traceback (most recent call last):
  File "./dnaPipeTE.py", line 699, in <module>
    Trinity(config['DEFAULT']['Trinity'], config['DEFAULT']['Trinity_memory'], args.cpu, config['DEFAULT']['Trinity_glue'], args.output_folder, sample_files, args.sample_number, args.contig_length)
  File "./dnaPipeTE.py", line 301, in **init**
    self.new_version_correction()
  File "./dnaPipeTE.py", line 329, in new_version_correction
    year = re.search('\d{4}', str(out)).group(0)
AttributeError: 'NoneType' object has no attribute 'group'

any idea how to fix this? my python knowledge is rather limited.
cheers
eckart

**Comment by clemgoub** [comment]
Hi Eckart, I'm so sorry I haven't noticed the messages on github and just picked them up now... Do you still need assistance with dnaPipeTE? My different projects have been leading me a bit away from this code for some time by I can try to spend some time to make some improvements. Let me know!

**Comment by estolle** [comment]
having a newer trinity compatible would be great, however, in the meantime I got things running with an old version. But I have the impression the changes would be small to fix it.

**Comment by clemgoub** [comment]
It's done now!!! =)
