### ISSUE TITLE
ggplot2

### ISSUE THREAD

**Issue by cslamo** [clemgoub/dnaPipeTE#10]
Almost at the end of the run I get this message:

```
#########################################
### OK, lets build some pretty graphs ###
#########################################
Drawing graphs...
null device 
          1 
null device 
          1 
null device 
          1 
null device 
          1 
Error in library(ggplot2) : there is no package called ‘ggplot2’
Execution halted
Done
```

Am I missing graphics as a result?

Thanks - Claudio

**Comment by clemgoub** [comment]
Hi Claudio,

It seems that you don't have ggplot2 installed with R.
You won't have the landscape graph done then.

To fix this, depending of your configuration the simplest is to launch manually R in your terminal and install ggplot2:

```
R
>install.packages("ggplot2", dep=T)
```

If you have a complex cluster installation that require root accesses to properly install the R packages on each nodes I recommend you to contact your system administrator.

Let me know how it goes!

Cheers,

Clément

**Comment by cslamo** [comment]
Tried that and got this:
```

> install.packages("ggplot2", dep=T)
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning message:
package ‘ggplot2’ is not available (for R version 3.0.2) 

```

**Comment by clemgoub** [comment]
Hi Claudio,

I would recommend to update to the latest version of R before moving forward. Your version might be too old.
If it still doesn't work then, let me know and I'll find another way around.

Clém

**Comment by clemgoub** [comment]
Hi Claudio, do you still have your issue with dnaPipeTE?
