### ISSUE TITLE
Why the single or low copy DNA is 100% in TEs_pipchart file?

### ISSUE THREAD

**Issue by wangj2009** [clemgoub/dnaPipeTE#16]
During test run, it runned smoothly for about 5 min, and produced files of Base_per_components.pdf and landscape.pdf, but the TEs_piechart.pdf file is a wholly gray figure and shows only "single or low copy DNA".

I run ./test_config.sh, it showed "java version < 1.8". But I actually installed java 10.0.1, perl 3.5, R 3.4.2, but GNU 2.12 in my environment.

    $python
     Python 3.5.1 (default, Jun 24 2016, 15:59:19) 
    [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux
 
    $java -version
    openjdk version "10.0.1" 2018-04-17
    OpenJDK Runtime Environment (build 10.0.1+10)
    OpenJDK 64-Bit Server VM (build 10.0.1+10, mixed mode)

The error files are as attached.
[TEs_piechart.pdf](https://github.com/clemgoub/dnaPipeTE/files/1948999/TEs_piechart.pdf)
[dnaPipeTE.52650.err.txt](https://github.com/clemgoub/dnaPipeTE/files/1949009/dnaPipeTE.52650.err.txt)
[dnaPipeTE.52650.out.txt](https://github.com/clemgoub/dnaPipeTE/files/1949010/dnaPipeTE.52650.out.txt)

**Comment by wangj2009** [comment]
Hi, thanks so much for your help. I got 29 contigs in Trinity.fasta.
The command is as followed and the Base_per_components and Landscape pdf are attached.

#!/bin/bash
#SBATCH --time=10000:00:00
#SBATCH --job-name=dnaPipeTE
#SBATCH --mail-type=ALL
#SBATCH --mail-user=
#SBATCH --error=dnaPipeTE.%j.err
#SBATCH --output=dnaPipeTE.%j.out

/opt/software/python3.5.1/bin/python3 /home/wang/scratch_dir/software/dnaPipeTE/dnaPipeTE.py \
    -input /home/wang/scratch_dir/software/dnaPipeTE/test/test_dataset.fastq \
    -output /home/wang/dnaPipeTE_test -genome_size 2000000 -genome_coverage 0.5 -sample_number 2


[Bases_per_components.pdf](https://github.com/clemgoub/dnaPipeTE/files/1952800/Bases_per_components.pdf)
[landscape.pdf](https://github.com/clemgoub/dnaPipeTE/files/1952801/landscape.pdf)

**Comment by clemgoub** [comment]
Hi again,

Everything seems fine indeed, except the annotation.
Try to add a cd (change directory) to the dnaPipeTE folder before executing the actual dnaPipeTE command in your scipt. 
It is likely that some related scripts doesn't work properly because of path issues.

Let's me know if that works,

Best,

Clément

**Comment by wangj2009** [comment]
Hi, it didn't work. The command I used is as followed:
    cd /home/wang/scratch_dir/software/dnaPipeTE
   /opt/software/python3.5.1/bin/python3 ./dnaPipeTE.py \
       -input  ./test/test_dataset.fastq \
       -output ./output_test1 -genome_size 2000000 -genome_coverage 0.5 -sample_number 2

**Comment by clemgoub** [comment]
Hi wangj2009, following up on your issue.
I'm sorry I did not ask you before since it is categorized as closed. 
Are you still having that issue?
