### ISSUE TITLE
Error getting after Run

### ISSUE THREAD

**Issue by raviraut206** [clemgoub/dnaPipeTE#17]
awk: fatal: cannot open file `/home/gnomeadmin/te_analysis/dnaPipeTE/dnaPipeTE//Trinity_run0/chrysalis/readsToComponents.out.sort' for reading (No such file or directory)
sed: can't read /home/gnomeadmin/te_analysis/dnaPipeTE/dnaPipeTE//Trinity_run1/Trinity.fasta: No such file or directory
awk: fatal: cannot open file `/home/gnomeadmin/te_analysis/dnaPipeTE/dnaPipeTE//Trinity_run1/Trinity.fasta' for reading (No such file or directory)
Traceback (most recent call last):
  File "./dnaPipeTE.py", line 698, in <module>
    RepeatMasker(config['DEFAULT']['RepeatMasker'], args.RepeatMasker_library, args.RM_species, args.cpu, args.output_folder, args.RM_threshold)
  File "./dnaPipeTE.py", line 381, in __init__
    self.repeatmasker_run()
  File "./dnaPipeTE.py", line 400, in repeatmasker_run
    with open(self.output_folder+"/Trinity.fasta.out", 'r') as trinity_handle:
FileNotFoundError: [Errno 2] No such file or directory: '/home/gnomeadmin/te_analysis/dnaPipeTE/dnaPipeTE//Trinity.fasta.out'

**Comment by clemgoub** [comment]
Hello,

Can you send me the full command line you use for this run?
Did the test run succed?

Thanks!

Clément

**Comment by raviraut206** [comment]
python3 ./dnaPipeTE.py -input SRR5045711_1.fastq.gz -output /home/gnomeadmin/te_analysis/dnaPipeTE/dnaPipeTE/ -cpu 14 -genome_size 389088367 -genome_coverage 0.5 -sample_number 1 >dnaPipeTE.log

**Comment by raviraut206** [comment]
**After test run, I got the following ...**

File /home/gnomeadmin/path/to/the/output_folder/Trinity.fasta appears to be empty.
Traceback (most recent call last):
  File "./dnaPipeTE.py", line 698, in <module>
    RepeatMasker(config['DEFAULT']['RepeatMasker'], args.RepeatMasker_library, args.RM_species, args.cpu, args.output_folder, args.RM_threshold)
  File "./dnaPipeTE.py", line 381, in __init__
    self.repeatmasker_run()
  File "./dnaPipeTE.py", line 400, in repeatmasker_run
    with open(self.output_folder+"/Trinity.fasta.out", 'r') as trinity_handle:
FileNotFoundError: [Errno 2] No such file or directory: '/home/gnomeadmin/path/to/the/output_folder/Trinity.fasta.out'

**Comment by raviraut206** [comment]
** I re-run it by making new out_foldet in /home/gnomeadmin. Following is the error I got ..**

File /home/gnomeadmin/output_folder//Trinity.fasta appears to be empty.
Traceback (most recent call last):
  File "./dnaPipeTE.py", line 698, in <module>
    RepeatMasker(config['DEFAULT']['RepeatMasker'], args.RepeatMasker_library, args.RM_species, args.cpu, args.output_folder, args.RM_threshold)
  File "./dnaPipeTE.py", line 381, in __init__
    self.repeatmasker_run()
  File "./dnaPipeTE.py", line 400, in repeatmasker_run
    with open(self.output_folder+"/Trinity.fasta.out", 'r') as trinity_handle:
FileNotFoundError: [Errno 2] No such file or directory: '/home/gnomeadmin/output_folder//Trinity.fasta.out'

**Comment by raviraut206** [comment]
The procedure I fallowed to run the dnaPipeTE.
1. download the SRR5045711 by using SRA toolkit by  ./prefetch  SRR5045711 
2. fastq-dump -A SRR5045711  --split-files --gzip
Download and Installed dnaPipeTE.
3. git clone https://github.com/clemgoub/dnaPipeTE
4. cd dnaPipeTE
nano init.sh
5. #set your GIRI username and password
GIRINST_USERNAME='my username'
GIRINST_PASSWORD='my password'
6. ./init.sh
7. cd bin/RepeatMasker
kept plantgenome.lib file in RepeatMasker/bin/Libraries
./configure
8. Enter path perl, RepeatMasker, trf, RMBlast, made RMBlast as default search engine.

Testing dnaPipeTE installation
9. cd ../../
./test_config.sh

Test run
10. cd /home/gnomeadmin/te_analysis/dnaPipeTE/dnaPipeTE 

python3 ./dnaPipeTE.py -input ./test/test_dataset.fastq -output /home/gnomeadmin/output_folder -genome_size 2000000 -genome_coverage 0.5 -sample_number 2

11. python3 ./dnaPipeTE.py -input SRR5045711_1.fastq.gz -output /home/gnomeadmin/te_analysis/dnaPipeTE/dnaPipeTE/ -cpu 14 -genome_size 389088367 -genome_coverage 0.5 -sample_number 1 >dnaPipeTE.log

**Comment by raviraut206** [comment]
Please See the attach file for dnaPipeTE.log

**Comment by clemgoub** [comment]
Hello,

I'm sorry I can't find your enclosed file! Also sorry for the late reply...

Best,

Clément

**Comment by raviraut206** [comment]
Please find the dnaPipeTE.log file in attach file.

**Comment by raviraut206** [comment]
_             _____ _         _______ ______                   
                 | |           |  __ (_)       |__   __|  ____|                  
               __| |_ __   __ _| |__) | _ __   ___| |  | |__                     
              / _` | '_ \ / _` |  ___/ | '_ \ / _ \ |  |  __|                    
             | (_| | | | | (_| | |   | | |_) |  __/ |  | |____                   
              \__,_|_| |_|\__,_|_|   |_| .__/ \___|_|  |______|                  
                                       | |                                       
                                       |_|                                       
                                                                                 
     De Novo Anssembly and Annotation PIPEline for Transposable Elements         
                              v.1.3.1_07.dec.2017                                      
                                                                                 
                                                                                                                                                                       
                                                               
                                                 :@@@@'     
                                               ,@@@@@@@@;   
                                              +@@@@@@@@@@,  
                                            .@@@@@@@@@@@@#  
                                    +@#.   '@@@@@@@@@@@@@#  
                                   #@@@@+`@@@@@@@@@@@@@@@,  
                                   '@@@@@@@@@@@@@@@@@@@@'   
                                    :@@@@@@@@@@@@@@@@@@.    
                                     :@@@@@@@@@@@@@@@+      
                                    #@@@@@@@@@;@@@@@,       
                                  ,@@@#`.@@@@@@#,@#         
                                 +@@@:    +@@@@@@,          
                               .@@@@       #@@@@@@#         
                              '@@@;       '@@@@@@@@@        
                            `@@@@`      `@@@@`:@@@@@        
                           ;@@@'       ;@@@'    +@+         
                          @@@@.       @@@@.                 
                        :@@@#       :@@@#                   
                       #@@@,       #@@@,                    
                     ,@@@#`@@'   ,@@@#                      
                    +@@@:'@@@@@:+@@@:                       
                  .@@@@`@@@@@@@@@@@                         
                 '@@@;:@@@@@@@@@@;                          
                #@@@`#@@@@@@@@@@`                           
               ,@@@;@@@@@@@@@@+                             
               #@@@@@@@@@@@@@.                              
               @@@@@@@@@@@@#                                
              .@@@@@@@@@@@,                                 
             +@@@@@@@@@@#                                   
             @@@@@@#+;.                                     
              +@@;                                          
                                                            
           Let's go !!!                                     
                                                            
Start time: Tue Aug 14 10:52:41 2018
generating trinity samples...
gz compression detected for SRR5045711_1.fastq.gz
counting reads number...
total number of reads: 163372
maximum number of reads to sample:  163372 
fastq :  SRR5045711_1.fastq
sampling 1 samples of max 163372 reads to reach coverage...
0/163372
100/163372
200/163372
300/163372
400/163372
500/163372
600/163372
700/163372
800/163372
900/163372
1000/163372
1100/163372
1200/163372
1300/163372
1400/163372
1500/163372
1600/163372
1700/163372
1800/163372
1900/163372
2000/163372
2100/163372
2200/163372
2300/163372
2400/163372
2500/163372
2600/163372
2700/163372
2800/163372
2900/163372
3000/163372
3100/163372
3200/163372
3300/163372
3400/163372
3500/163372
3600/163372
3700/163372
3800/163372
3900/163372
4000/163372
4100/163372
4200/163372
4300/163372
4400/163372
4500/163372
4600/163372
4700/163372
4800/163372
4900/163372
5000/163372
5100/163372
5200/163372
5300/163372
5400/163372
5500/163372
5600/163372
5700/163372
5800/163372
5900/163372
6000/163372
6100/163372
6200/163372
6300/163372
6400/163372
6500/163372
6600/163372
6700/163372
6800/163372
6900/163372
7000/163372
7100/163372
7200/163372
7300/163372
7400/163372
7500/163372
7600/163372
7700/163372
7800/163372
7900/163372
8000/163372
8100/163372
8200/163372
8300/163372
8400/163372
8500/163372
8600/163372
8700/163372
8800/163372
8900/163372
9000/163372
9100/163372
9200/163372
9300/163372
9400/163372
9500/163372
9600/163372
9700/163372
9800/163372
9900/163372
10000/163372
10100/163372
10200/163372
10300/163372
10400/163372
10500/163372
10600/163372
10700/163372
10800/163372
10900/163372
11000/163372
11100/163372
11200/163372
11300/163372
11400/163372
11500/163372
11600/163372
11700/163372
11800/163372
11900/163372
12000/163372
12100/163372
12200/163372
12300/163372
12400/163372
12500/163372
12600/163372
12700/163372
12800/163372
12900/163372
13000/163372
13100/163372
13200/163372
13300/163372
13400/163372
13500/163372
13600/163372
13700/163372
13800/163372
13900/163372
14000/163372
14100/163372
14200/163372
14300/163372
14400/163372
14500/163372
14600/163372
14700/163372
14800/163372
14900/163372
15000/163372
15100/163372
15200/163372
15300/163372
15400/163372
15500/163372
15600/163372
15700/163372
15800/163372
15900/163372
16000/163372
16100/163372
16200/163372
16300/163372
16400/163372
16500/163372
16600/163372
16700/163372
16800/163372
16900/163372
17000/163372
17100/163372
17200/163372
17300/163372
17400/163372
17500/163372
17600/163372
17700/163372
17800/163372
17900/163372
18000/163372
18100/163372
18200/163372
18300/163372
18400/163372
18500/163372
18600/163372
18700/163372
18800/163372
18900/163372
19000/163372
19100/163372
19200/163372
19300/163372
19400/163372
19500/163372
19600/163372
19700/163372
19800/163372
19900/163372
20000/163372
20100/163372
20200/163372
20300/163372
20400/163372
20500/163372
20600/163372
20700/163372
20800/163372
20900/163372
21000/163372
21100/163372
21200/163372
21300/163372
21400/163372
21500/163372
21600/163372
21700/163372
21800/163372
21900/163372
22000/163372
22100/163372
22200/163372
22300/163372
22400/163372
22500/163372
22600/163372
22700/163372
22800/163372
22900/163372
23000/163372
23100/163372
23200/163372
23300/163372
23400/163372
23500/163372
23600/163372
23700/163372
23800/163372
23900/163372
24000/163372
24100/163372
24200/163372
24300/163372
24400/163372
24500/163372
24600/163372
24700/163372
24800/163372
24900/163372
25000/163372
25100/163372
25200/163372
25300/163372
25400/163372
25500/163372
25600/163372
25700/163372
25800/163372
25900/163372
26000/163372
26100/163372
26200/163372
26300/163372
26400/163372
26500/163372
26600/163372
26700/163372
26800/163372
26900/163372
27000/163372
27100/163372
27200/163372
27300/163372
27400/163372
27500/163372
27600/163372
27700/163372
27800/163372
27900/163372
28000/163372
28100/163372
28200/163372
28300/163372
28400/163372
28500/163372
28600/163372
28700/163372
28800/163372
28900/163372
29000/163372
29100/163372
29200/163372
29300/163372
29400/163372
29500/163372
29600/163372
29700/163372
29800/163372
29900/163372
30000/163372
30100/163372
30200/163372
30300/163372
30400/163372
30500/163372
30600/163372
30700/163372
30800/163372
30900/163372
31000/163372
31100/163372
31200/163372
31300/163372
31400/163372
31500/163372
31600/163372
31700/163372
31800/163372
31900/163372
32000/163372
32100/163372

	Error, cannot locate Trinity-specific tool: ParaFly in the PATH setting: /home/gnomeadmin/te_analysis/dnaPipeTE/dnaPipeTE/bin/trinityrnaseq-Trinity-v2.5.1/trinity-plugins/BIN:/home/gnomeadmin/bin:/home/gnomeadmin/.local/bin:/home/gnomeadmin/te_analysis/dnapipeTE/dnaPipeTE/bin/OpenJDK-1.8.0.141-x86_64-bin/bin:/home/gnomeadmin/anaconda3/bin:/home/gnomeadmin/bin:/home/gnomeadmin/.local/bin:/home/gnomeadmin/miniconda2/bin:/bin:/home/gnomeadmin/bin:/home/gnomeadmin/.local/bin:/usr/local/bin/bin:/opt/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/gnomeadmin/software/fasta-35.4.12/bin/,  be sure to install Trinity by running 'make' in the base installation directory

RepeatMasker version open-4.0.7
Search Engine: NCBI/RMBLAST [ 2.2.27+ ]
Master RepeatMasker Database: /home/gnomeadmin/te_analysis/dnaPipeTE/dnaPipeTE/bin/RepeatMasker/Libraries/RepeatMaskerLib.embl ( Complete Database: dc20170127-rb20170127 )


File /home/gnomeadmin/output_folder//Trinity.fasta appears to be empty.

194550696 bases sampled in 32139 reads 
s_SRR5045711_1.fastq done.
['s0_SRR5045711_1.fastq.fasta']
###################################
### TRINITY to assemble repeats ###
###################################

***** TRINITY iteration 1 *****

Selecting reads for Trinity iteration number 1...
Done

Trinity iteration 1 Done'
renaming Trinity output...
done
/home/gnomeadmin/output_folder//Annotation/one_RM_hit_per_Trinity_contigs
/home/gnomeadmin/output_folder//Annotation/Best_RM_annot_80-80
/home/gnomeadmin/output_folder//Annotation/Best_RM_annot_partial
#######################################
### REPEATMASKER to anotate contigs ###
#######################################

**Comment by clemgoub** [comment]
Hi!

It looks like Trinity is not properly installed, this could be due to a problem specific to this program with your machine. 
Try to manually compile Trinity by running:

`make`

In the Trinity folder located in dnaPipeTE/bin

Let me know it this returns you some error. If not, try another run after. We'll find out what is wrong!

Best,

Clément

**Comment by clemgoub** [comment]
Closing this issue since it concerns the non-container version. Please DM if further support is needed. Thank you!
