### ISSUE TITLE
Feature Request: RepeatMasker compatible fasta headers

### ISSUE THREAD

**Issue by rotifergirl** [clemgoub/dnaPipeTE#18]
Hi Clement,

Just a small request based on the work I'm doing. I'm using the dnaPipeTE contigs as a custom library of repeats for my organism for repeatmasker, and I've had to go through and edit the fasta headers in the Annotation file to include the classification in a format compatible with repeatmasker.

Currently an example of a fasta header here is:

 `>DNA_comp_TRINITY_DN16970_c0_g1_i1`

and for repeatmasker compatibility it would look like

 `>DNA_comp_TRINITY_DN16970_c0_g1_i1#DNA`

For deeper level classification it might read

 `>DNA_comp_TRINITY_DN16970_c0_g1_i1#DNA/Helitron`

for example.

As it stands, I have gotten around this with a sed command, but other users may also appreciate this feature, be it as an option or as a default.

Thanks again for such a great tool and for helping out with any previous issues too!

**Comment by clemgoub** [comment]
Hello!

Sorry for my delayed reply! It sounds like an easy fix. 

I will definitely add this for the next update, thank you for the suggestion!
The update, I hope, will happen soon with the most recent version of Trinity and a few new features I am working on.

Cheers,

Clément

**Comment by andreaswallberg** [comment]
Hi @clemgoub !

Was this implemented. I recently tried DNApipeTE and it looks like my output headers are not "RepeatMasker ready".

This is an easy fix for me to do myself, but which of the accessory files would you recommend to insert the "#Class/Order" tag?

**Comment by clemgoub** [comment]
Hi Andreas,

Are you referring to the dnaPipeTE contigs, located in the file `Trinity.fasta`?
You can find the annotation given to these contigs in the file `reads_per_component_and_annotations` 
If there is no annotation at all, do you have a file `Trinity.fasta.out` and if yes, does it have any lines?

From that, we will be able to troubleshoot!

Cheers,

Clément
