### ISSUE TITLE
gz compression of inputfiles

### ISSUE THREAD

**Issue by estolle** [clemgoub/dnaPipeTE#2]
Hi again.

I seem to have an issue with the handling of compressed fastq input and get this error:
Start time: Fri Sep  9 16:26:32 2016
gz compression detected for /reads/xy.fastq.gz
counting reads number...Traceback (most recent call last):
  File "/progz/dnaPipeTE/dnaPipeTE.py", line 697, in <module>
    Sampler = FastqSamplerToFasta(args.input_file, args.sample_size, args.genome_size, args.genome_coverage, args.sample_number, args.output_folder, False)
  File "/progz/dnaPipeTE/dnaPipeTE.py", line 156, in **init**
    self.get_sampled_id(self.fastq_R1)
  File "/progz/dnaPipeTE/dnaPipeTE.py", line 188, in get_sampled_id
    with gzip.open(file_name+".gz", 'rt') as file1 :
  File "/usr/lib64/python3.2/gzip.py", line 46, in open
    return GzipFile(filename, mode, compresslevel)
  File "/usr/lib64/python3.2/gzip.py", line 156, in **init**
    raise IOError("Mode " + mode + " not supported")
IOError: Mode rt not supported

the input was xy.fastq.gz file which was generate by "gzip xy.fastq".
any idea if its a python problem or dnapiteTE problem?

**Comment by clemgoub** [comment]
Hi, I just found out your issue. Sorry for the delay. Do you still encounter it?

**Comment by estolle** [comment]
Hi again.

I could not fix it in the end, but got the pipe running by simply decompressing the input.
