### ISSUE TITLE
RepeatMasker library

### ISSUE THREAD

**Issue by nrius** [clemgoub/dnaPipeTE#22]
Hi!

I am installing dnaPipeTE, following all the steps and including the giri username and subscription. However, I got these errors:

When runnin init.sh:
~~~~
(...)

Saving to: ‘RepBaseRepeatMaskerEdition-20170127.tar.gz’

RepBaseRepeatMaskerEdition-20170127.tar.gz    100%[===============================================================================================>]   9,43K  --.-KB/s    in 0,03s   

2019-08-06 14:00:44 (296 KB/s) - ‘RepBaseRepeatMaskerEdition-20170127.tar.gz’ saved [9661/9661]


gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

##################################################################################################
installation of dependencies done, now run the ./configure script in the ./bin/RepeatMasker folder

~~~~

And if I continue with the dependencies configuration and then try ./test_config.sh

~~~~
./test_config.sh 
This is the test script for dnaPipeTE
                  ***                

We will test a few dependancies to be sure tha the pipeline run properly


Testing Java...
java version OK!


Testing RepeatMasker Libraries...
RepeatMasker.lib doesn't include the Repbase sequences! Follow instruction to install RepeatMasker libraries on https://github.com/clemgoub/dnaPipeTE
~~~~

Do you know how I can solve it? or where the problem may be?

Thanks

**Comment by clemgoub** [comment]
Hi nrius,

Sorry you are encountering issues with dnaPipeTE. Repbase changed last year to turn into a subscription-based system. Since then, I had not tested how this install works, which can be an issue.
In your case it seems that you are downloading something that is not a tar.gz archive. I have to go by the dnaPipeTE script to tell you more. 

In the mean time, you can look at the file downloaded: is it a real archive or is it an empty file?

I will come back to you ASAP after I do checks on my side!

Clément

**Comment by nrius** [comment]
Hi Clément,

Thanks for your prompt answer.

You are right, I copied the file to another directory and tried to extract
in. However I got the same result.
----------------




*tar -xvzf RepBaseRepeatMaskerEdition-20170127.tar.gz gzip: stdin: not in
gzip formattar: Child returned status 1tar: Error is not recoverable:
exiting now*
----------------

I downloaded the file from giri and this version can be extracted:

----------



*tar -xvzf RepBaseRepeatMaskerEdition-20181026.tar.gz
Libraries/Libraries/RMRBSeqs.emblLibraries/README.RMRBSeqs*
----------

So I removed the old tar.gz and copied the new one. I configured
RepeatMasker and run ./test_config.sh. I still ahve an error, but now it is
different:
-----------












*./test_config.sh This is the test script for dnaPipeTE
***                We will test a few dependancies to be sure tha the
pipeline run properlyTesting Java...java version OK!Testing RepeatMasker
Libraries...RepeatMasker.lib doesn't include the Repbase sequences! Follow
instruction to install RepeatMasker libraries on
https://github.com/clemgoub/dnaPipeTE
<https://github.com/clemgoub/dnaPipeTE>*
----------------------------

Inside the README.RMRBSeqs I saw that they have changed the libraries. Is
this change previous to dnaPipeTE?

------








*COMPATIBILITY WITH OLDER VERSIONS OF REPEATMASKERThis library distribution
involves a major shift away from a monolithic( one source ) library format
and embraces the notion that libraries mayincreasingly come from multiple
sources.  Unfortunately this requireschanges in the library structures that
will not work with previous versionsof RepeatMasker ( 4.0.6 and earlier ).
We have not removed support for older libraries and versions 20140131 and
on should continue to work withthe latest releases of RepeatMasker*

-----

Thanks,

Nuria





Nuria Rius Camps

**Comment by nrius** [comment]
Hello again,

I have tried other things that didn't work, but may help you figure out a
solution.

In the directory /mypath/dnaPipeTE/bin/RepeatMasker/Libraries, after
running init.sh (exiting with gzip error) and configure RepeatMasker I had
the following files. I have checked that in RepeatMasker.lib there were 425
sequences, hence trigging the error of *test_config.sh*





* (if [[ $(grep -c '>' ./bin/RepeatMasker/Libraries/RepeatMasker.lib) > 425
]]; then echo "Repbase Libraries are properly installed!"else echo
"RepeatMasker.lib doesn't include the Repbase sequences! Follow instruction
to install RepeatMasker libraries on https://github.com/clemgoub/dnaPipeTE
<https://github.com/clemgoub/dnaPipeTE>"fi)*

*Libraries directory created automatically by init.sh and RM configure:*


















*total 1,6G-rw-r--r-- 1 rius rius 4,3K mag 28  2009
RepeatPeps.readme-rw-r--r-- 1 rius rius 9,9M gen 31  2014
RepeatPeps.lib-rw-r--r-- 1 rius rius  22M ago  7  2015
RepeatAnnotationData.pm-rw-r--r-- 1 rius rius 1,5G set 24  2015
Dfam.hmm-rw-r--r-- 1 rius rius  62M ago 30  2016 taxonomy.dat-rw-r--r-- 1
rius rius  17M gen 29  2017 RMRBMeta.embl-rw-r--r-- 1 rius rius  214 gen 29
 2017 README.meta-rw-r--r-- 1 rius rius 208K gen 29  2017
DfamConsensus.embl-rw-rw-r-- 1 rius rius 205K ago  6 15:36
RepeatMaskerLib.embl-rw-rw-r-- 1 rius rius 127K ago  6 15:36
RepeatMasker.lib-rw-rw-r-- 1 rius rius 5,2K ago  6 15:37
RepeatMasker.lib.nin-rw-rw-r-- 1 rius rius  43K ago  6 15:37
RepeatMasker.lib.nhr-rw-rw-r-- 1 rius rius  28K ago  6 15:37
RepeatMasker.lib.nsq-rw-rw-r-- 1 rius rius 9,1M ago  6 15:37
RepeatPeps.lib.psq-rw-rw-r-- 1 rius rius  83K ago  6 15:37
RepeatPeps.lib.pin-rw-rw-r-- 1 rius rius 1,5M ago  6 15:37
RepeatPeps.lib.phr*


I looked at this directory from a previous version ( v.1.2_04-2016 ) a
colleague had, and copied the content into the /Libraries directory. I
thought this was unlikely to work as the RepeatMasker library should be the
same verison of RepeatMasker. Anyway, now the *RepeatMasker.lib* in the
library directory has 35996 sequences, but the test_config.sh error is
triggered all the same, and don't know why.

*total 1,8G*













*-rwxr-xr-x 1 root root  96M ago  7 17:08 RepeatMasker.lib-rwxr-xr-x 1 root
root 137M ago  7 17:08 RepeatMaskerLib.embl-rw-r--r-- 1 root root 4,6M ago
 7 17:08 RepeatMasker.lib.nhr-rw-r--r-- 1 root root 422K ago  7 17:08
RepeatMasker.lib.nin-rw-r--r-- 1 root root  24M ago  7 17:08
RepeatMasker.lib.nsq-rwxr-xr-x 1 root root 3,6K ago  7 17:08
README-rwxr-xr-x 1 root root 1,5G ago  7 17:08 Dfam.hmm-rwxr-xr-x 1 root
root  62M ago  7 17:08 taxonomy.dat-rwxr-xr-x 1 root root  22M ago  7 17:08
RepeatAnnotationData.pm-rwxr-xr-x 1 root root 9,9M ago  7 17:08
RepeatPeps.lib-rw-r--r-- 1 root root 1,5M ago  7 17:08
RepeatPeps.lib.phr-rw-r--r-- 1 root root  83K ago  7 17:08
RepeatPeps.lib.pin-rw-r--r-- 1 root root 9,1M ago  7 17:08
RepeatPeps.lib.psq-rwxr-xr-x 1 root root 4,3K ago  7 17:08
RepeatPeps.readme*

I hope this can help you somehow to understand what is happening.
Thanks,


Nuria

Nuria Rius Camps

**Comment by clemgoub** [comment]
Hi Nuria,
Sorry for my late reply, I am currently traveling.
It is possible that the new libraries does not work with this config script while being effectively installed. If you did the RM install following the instructions and this did not return any error, you might have the libraries effe installed. Did you try to run dnaPipeTE anyways?

Clément

**Comment by nrius** [comment]
Hi Clément,

Sorry for the late reply, I have been trying different solutions. I got
dnaPipeTE installed on a cluster I have access and this time the run with
the test files exited successfully. However, the Counts.txt file showed
there was no classification per Superfamilies (see below) and probably
because of that the pie chart was not done. I thought it could be because
of low coverage and I've tried with my human data using different
combinations. The first result I've got so far, with 4 million reads and 3
samplings, yielded a similar Counts.txt file (see below). Do you know if
this indicates a problem with the libraries or something else? Is there
something I can check?

Thanks for your help
Nuria


------Test-------

LTR 0
LINE 0
SINE 0
DNA 0
MITE 0
Helitron 0
rRNA 0
Low_Complexity 0
Satellite 0
Tandem_repeats 0
Simple_repeat 0
others 0
na 0
Others 0
Total 987936
------------------

-------human data------------------
LTR 0
LINE 0
SINE 0
DNA 0
MITE 0
Helitron 0
rRNA 0
Low_Complexity 0
Satellite 0
Tandem_repeats 0
Simple_repeat 0
others 0
na 0
Others 0
Total 596461348
--------------------------------------




Nuria Rius Camps

**Comment by clemgoub** [comment]
Hi Nuria,

Glad you made some progress with the install. What you think is very likely. Can you verify the syntax in your repbase fasta file? The format of the header must be:

`>RepeatName#Class/subclass`

the # is very important, and the Class and subclass names must be present in the file `new_list_of_RM_superclass_colors_sortedOK` present in your dnaPipeTE folder.

Let me know if this helped,

Cheers,

Clément

**Comment by nrius** [comment]
Hi Clément,
In "dnaPipeTE/bin/RepeatMasker/Libraries/RepeatMasker.lib" the header is
the expected one, this is an example: ">FordP_Test-1N2#DNA/hAT-Tip100  [S:]
" .
"dnaPipeTE/new_list_of_RM_superclass_colors_sortedOK" is the same as the
one in your GitHub.

Could it be something else?

Thanks,

Nuria





Nuria Rius Camps

**Comment by clemgoub** [comment]
Hi!

If I understand correctly you never had a pieChard and Counts working, even with a test run with test data right?

Clém

**Comment by nrius** [comment]
Exactly. Although when dnaPipeTE finishes it doesn't give errors:
---------------------------------------------------------
Drawing graphs...
Done
Removing Trinity runs files...
done
Finishin time: Mon Sep  2 20:13:41 2019
########################
#   see you soon !!!   #
########################
-------------------------------------------------------

**Comment by clemgoub** [comment]
I see... Can you send me your whole logs and command?

**Comment by nrius** [comment]
Sure,
Here are the commands and the logs for the test run (dnaPipeTE_2.job and
nr_dna_5_2.o796095) and the run with my data (dnaPipeTE_5_2.job and
nr_dna_5_2.o796095).

Thanks
Nuria





Nuria Rius Camps

**Comment by clemgoub** [comment]
Hi,

I'm sorry, I didn't get the files. You can email them to me at cg629 @ cornell.edu

**Comment by nrius** [comment]
Hi Clément,
let me know if you still have problems to download them.

Thanks





Nuria Rius Camps

**Comment by clemgoub** [comment]
Yes I'm sorry I didn't got anything...

**Comment by nrius** [comment]
Hi,
Do you mean you don't understand why this happened or that you didn't
receive the files?

Thanks anyway,

Nuria




Nuria Rius Camps

**Comment by jcerca** [comment]
Dear Clément and Nuria,

dnaPipeTE seems like a wonderful pipeline - I am really looking forward to installing it and getting it running as part of my work.

Not sure if you ever got to solve this, but I did, so posting it so it is available to everyone.

This was the error I got
```
2020-12-19 22:01:46 (132 MB/s) - ‘RepBaseRepeatMaskerEdition-20170127.tar.gz’ saved [9661/9661]
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```


When I find this file, it seems empty:

```
find . | grep RepBaseRepeatMaskerEdition-20170127.tar.gz
 ./bin/RepeatMasker/RepBaseRepeatMaskerEdition-20170127.tar.gz

ls -lah  ./bin/RepeatMasker/RepBaseRepeatMaskerEdition-20170127.tar.gz
-rwxrwxrwx 1 josepc posixgroup 9.5K Mar 21  2019 RepBaseRepeatMaskerEdition-20170127.tar.gz

tar xvzf  ./bin/RepeatMasker/RepBaseRepeatMaskerEdition-20170127.tar.gz
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

So then I googled: "RepBaseRepeatMaskerEdition-20170127.tar.gz" and came with the following link:
https://github.com/yjx1217/RMRB

& did the following:
```
cd ./bin/RepeatMasker
wget https://github.com/yjx1217/RMRB/raw/master/RepBaseRepeatMaskerEdition-20170127.tar.gz ## obtained from the URL above
mv RepBaseRepeatMaskerEdition-20170127.tar.gz.1 RepBaseRepeatMaskerEdition-20170127.tar.gz  # I do this since wget generated a "*.1" file.
```

This did not work, so I tried understanding what init.sh was doing with the repeatmask library.

```
cd ../../
grep gz init.sh
###grep result
curl -k -L https://github.com/trinityrnaseq/trinityrnaseq/archive/Trinity-v2.5.1.tar.gz -o Trinity-v2.5.1.tar.gz
tar -zxvf Trinity-v2.5.1.tar.gz
curl -k -L  ftp://ftp.ncbi.nlm.nih.gov/blast/executables/rmblast/2.2.28/ncbi-rmblastn-2.2.28-x64-linux.tar.gz -o ncbi-rmblastn-2.2.28-x64-linux.tar.gz
tar -xvf ncbi-rmblastn-2.2.28-x64-linux.tar.gz
rm ncbi-rmblastn-2.2.28-x64-linux.tar.gz
curl -k -L ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.2.28/ncbi-blast-2.2.28+-x64-linux.tar.gz -o ncbi-blast-2.2.28+-x64-linux.tar.gz
tar -xvf ncbi-blast-2.2.28+-x64-linux.tar.gz
rm ncbi-blast-2.2.28+-x64-linux.tar.gz
curl -k -L http://repeatmasker.org/RepeatMasker-open-4-0-7.tar.gz -o RepeatMasker-open-4-0-7.tar.gz
tar -xvf RepeatMasker-open-4-0-7.tar.gz
wget http://www.girinst.org/server/RepBase/protected/repeatmaskerlibraries/RepBaseRepeatMaskerEdition-20170127.tar.gz --password=$GIRINST_PASSWORD  --user=$GIRINST_USERNAME
mv RepBaseRepeatMaskerEdition-20170127.tar.gz RepeatMasker/
tar -zxvf RepBaseRepeatMaskerEdition-20170127.tar.gz
```

This tells me that it downloads it everytime I run the `bash ./init.sh` command. So I basically used nano and literally replaced the line:
```
wget http://www.girinst.org/server/RepBase/protected/repeatmaskerlibraries/RepBaseRepeatMaskerEdition-20170127.tar.gz --password=$GIRINST_PASSWORD  --user=$GIRINST_USERNAME
```
with:
```
wget https://github.com/yjx1217/RMRB/raw/master/RepBaseRepeatMaskerEdition-20170127.tar.gz
```

and it worked. I still have some trinity issues, though - hoping to solve it soon.

**Comment by clemgoub** [comment]
Dear José,

I'm sorry for the delays. I recently moved from the US to Canada and cannot provide a very fast support on dnaPipeTE at the moment...
Unfortunately, dnaPipeTE needs a big update... In the meantime, please DM me and I will help you with the Repbase libraries. 

Best,

Clément

**Comment by jcerca** [comment]
Hi Clément,

thank you for your answer. I managed to solve it.. was pointing out to the wrong perl/lib/path - newbie mistake!

Looking forward to see that update. TEs are a fascinating part of genomics and I hope to answer many fascinating questions with dnaPipeTE :)

Best,
José
