### ISSUE TITLE
Repbase Libraries

### ISSUE THREAD

**Issue by signor-molevol** [clemgoub/dnaPipeTE#24]
I've successfully installed dnaPipeTE on a cluster and my home computer, but I am still getting this message when I run test_config.sh:

Testing RepeatMasker Libraries...
RepeatMasker.lib doesn't include the Repbase sequences! Follow instruction to install RepeatMasker libraries on https://github.com/clemgoub/dnaPipeTE

This is what the library directory looks like on the cluster:

Libraries]$ ls -l
total 1599056
-rw-r--r-- 1      212876 Jan 28  2017 DfamConsensus.embl
-rw-r--r-- 1  1510837557 Sep 24  2015 Dfam.hmm
-rw-r--r-- 1        214 Jan 28  2017 README.meta
-rw-r--r-- 1 22475384 Aug  7  2015 RepeatAnnotationData.pm
-rw-r--r-- 1   129371 Sep  5 13:04 RepeatMasker.lib
-rw-r--r-- 1     209744 Sep  5 13:04 RepeatMaskerLib.embl
-rw-r--r-- 1   43039 Sep  5 13:09 RepeatMasker.lib.nhr
-rw-r--r-- 1 5272 Sep  5 13:09 RepeatMasker.lib.nin
-rw-r--r-- 1  28191 Sep  5 13:09 RepeatMasker.lib.nsq
-rw-r--r-- 1 0325957 Jan 31  2014 RepeatPeps.lib
-rw-r--r-- 1 1516945 Sep  5 13:09 RepeatPeps.lib.phr
-rw-r--r-- 1  84520 Sep  5 13:09 RepeatPeps.lib.pin
-rw-r--r-- 1 9463396 Sep  5 13:09 RepeatPeps.lib.psq
-rw-r--r-- 1 4401 May 28  2009 RepeatPeps.readme
-rw-r--r-- 1 17204287 Jan 28  2017 RMRBMeta.embl
-rw-r--r-- 1 64450715 Aug 29  2016 taxonomy.dat

I have a working GIRI login. Any advice?

**Comment by clemgoub** [comment]
Hello,

Repbase has changed a bit since the latest update of dnaPipeTE. Did you still try a test run? If so do you have annotation or everything is at 0 ?

More and more users are reporting difficulties with Repbase, I have to investigate this in details. In the meantime, keep me posted and I will help you!

Cheers,

Clément

**Comment by hstern2** [comment]
I couldn't find the 20170127 version of the repbase libraries on the GIRI website (are these still available?) I tried with RepBaseRepeatMaskerEdition-20181026 but got errors.

**Comment by clemgoub** [comment]
Hello,

Unfortunately RepBase is not on a subscription basis. We are working on a new dnaPipeTE version which should be independent from RepBase. I will DM you with a custom solution!

Cheers,

Clément
