### ISSUE TITLE
Best_RM_annot_80

### ISSUE THREAD

**Issue by Tidler123** [clemgoub/dnaPipeTE#27]
Hi,
I'm trying to work with the Best_RM_annot_80 files.
My problem is I can't really make sense of some of the columns. I also couldn't find any hint of what the headers for that file might be.
Is there a good source for that? I've looked at the RM website as well as dnaPipeTE READ.ME file and several articles.

Thanks in advance

**Comment by clemgoub** [comment]
Hi,

I'm sorry for that. The columns are:

1 - dnaPipeTE contig name
2 - contig size
3 - Proportion of the contig covered by a Repeat Masker annotation
4 - Database hit (TE name)
5 - Database hit (class/superfamily)
6 - Database consensus size
7 - Hit span on database consensus
8 - Proportion of the database consensus covered by the dnaPipeTE contig

Hope it helps! I'll update the README soon! Thanks for contacting me!

Clém
