### ISSUE TITLE
Calculating TEs divergence

### ISSUE THREAD

**Issue by Tidler123** [clemgoub/dnaPipeTE#28]
Hi,
I have used dnaPipeTE on a large collection of wild barley I have, comprised of several populations of the same species. I've used the cultivated barley 'repbase' database as reference. 
I was wondering whether the reads_landscape files can help in assessing population, rather than species, divergence (based on TEs) and if so, should I be using a different species database as reference?
Also, the landscape graph was not produced for any of the samples I've analysed although the landscape_reads files were. Is that an indication of the process not finishing?

Thank you for your time

**Comment by clemgoub** [comment]
Hi there,

I am so sorry I missed this thread. Please let me know if you need further assistance by re-opening this issue.

Best,

Clément
