### ISSUE TITLE
Trinity iteration errors

### ISSUE THREAD

**Issue by swarris** [clemgoub/dnaPipeTE#3]
The program gives this error:
awk: fatal: cannot open file 'output/Trinity_run0/chrysalis/readsToComponents.out.sort' for reading (No such file or directory)

This can be traced back to 'trinity_iteration' and 'select_reads', where in some cases 'iteration+1' is used and in other cases 'iteration': file naming is not consistent. This 'iteration'-error is easily fixed, however the underlying problem then still remains. 'awk' expect output from trinity, but in the first iteration this output does not exists. 
In the code there is this call: 'self.trinity_iteration(0)' (line 298), however iteration '0' is not handled differently within that method. Maybe some code got lost somehow?

**Comment by clemgoub** [comment]
Hello, sorry for my late response on this thread... I just noticed these notifications on github...
This error is actually a small bug that does not influence the calculations in dnaPipeTE. We plan to fix it in the next update! Thanks!
