### ISSUE TITLE
Landscape error

### ISSUE THREAD

**Issue by mylena-s** [clemgoub/dnaPipeTE#30]
Hi clement, 
I have this issue when i look at the landscape graph. I tried different coverages for a ~2GB genome, and as the number of "families" is high, the landscape graph is not well constructed. Im sending you three pictures showing the problem. I guess It's due to the height parameter in the R script, but as Im not used to work with R-language I'm unable to solve it efficiently. 
Also, I wanted to know if there is some way re-run the landscapes.R script. I guess the input file is the reads_landscape  and factors_and_colors... but are there others?
[landscape02X.pdf](https://github.com/clemgoub/dnaPipeTE/files/4154234/landscape02X.pdf)
[landscape008X.pdf](https://github.com/clemgoub/dnaPipeTE/files/4154235/landscape008X.pdf)
[landscape025X.pdf](https://github.com/clemgoub/dnaPipeTE/files/4154236/landscape025X.pdf)

**Comment by clemgoub** [comment]
Ho I see! The problem you have is that there is so much subfamilies to show that the graph is not found. I attach a modified version of the script to re-process the graph without the legend. Below is the command line to reprocess the graph. Execute this line from the `dnaPipeTE` main folder (as you run dnaPipeTE).

`Rscript landscapes.R reads_landscape factors_and_colors blast_reads.counts`

It will create a new pdf with the new graph. Please let me know if you have any trouble.

Cheers,

Clément

```rscript
#!/usr/bin/Rscript

####################################################
# This is a modification of the Landscape.R script #
# to remove legend when it is too large to display #
#                date: 02/04/2020                  #
####################################################

library(ggplot2)

#read the table with reads and identity selected for landscape analysis
Args = commandArgs()

file1 = Args[6]
file2 = Args[7]
file3 = Args[8]

land = read.table(file1)
ttl = read.table(file3)
ttl = ttl[1]

#read.table("reads_landscape")->land
names(land)=c("id", "annot", "fam1", "fam")
land$div=100-land$id

#read the corresponding factor order and color table
fac_col = read.table(file2)

#print(head(land))
#print(fac_col)

#order factors and colors
land$fam1=factor(land$fam1, levels=as.character(fac_col$V1))
#print(as.numeric(ttl))

#plot the landscape graph
ggplot(land, aes(div, fill=fam1))
  +geom_histogram(binwidth=1.1)
  +labs(list(x="Divergence from dnaPipeTE contig (%)", y="Genome percent"))
  +coord_cartesian(xlim = c(0, 35))+scale_fill_manual(values=as.character(fac_col$V3))
  +guides(fill=guide_legend(ncol=3))+theme(legend.direction ="vertical",legend.position = "bottom")
  +scale_y_continuous(labels=function(x)signif(x/as.numeric(ttl)*100, 3))
  +theme(legend.position = "none") # removes legend - comment this line to add legend

ggsave("landscape.pdf", height=12, width=6)
```

**Comment by mylena-s** [comment]
Thanks for solving it!
Regards

**Comment by clemgoub** [comment]
No problem!
