### ISSUE TITLE
about the output file reads_per_component_and_annotation

### ISSUE THREAD

**Issue by abshah** [clemgoub/dnaPipeTE#33]
Hi dnaPipeTE devs!

I would like to understand all the columns in the output file reads_per_component_and_annotation. From the manual, I understand that there are 5 columns: read counts, aligned bases, contig name, RM annotation and proportion of contig with RM hit. However, my reads_per_component_and_annotation file contains 6 columns. 
For example :

````
168 24506 comp_TRINITY_DN4252_c0_g1_i2 2983 Gypsy-32_LMi-I LTR/Gypsy 0.7562856185048609
168 24940 comp_TRINITY_DN4286_c3_g4_i4
166 23137 comp_TRINITY_DN4278_c3_g2_i1 1457 Penelope-43_LMi LINE/Penelope 0.9993136582017845
165 13058 comp_TRINITY_DN2925_c0_g1_i1 218 RTE-53_LMi LINE/RTE-BovB 0.5504587155963303
165 22865 comp_TRINITY_DN4295_c12_g1_i1 339 CR1-4_LMi LINE/CR1 0.9970501474926253
165 24465 comp_TRINITY_DN4223_c5_g1_i14 509 Mariner-10_LMi DNA/TcMar-Tc1 0.7033398821218074
158 23363 comp_TRINITY_DN4009_c0_g3_i1 3032 Gypsy-53_LMi-I LTR/Gypsy 0.9993403693931399
````

I would like to know what is the number right after the contig name.

Best Wishes,

Abhijeet

**Comment by clemgoub** [comment]
Hello Abhijeet,

Sorry for the issue. The column are:

1- reads mapped
2- bp mapped
3- which dnaPipeTE/Trinity contig (target)
4- dnaPipeTE/trinity contig size
5- Repbase/database hit (family name)
6- Repbase/database hit (class/superfamily)

I hope to fix all inconsistencies in the manual by this summer, however please keep reporting if you find more!

Cheers,

Clément

**Comment by abshah** [comment]
Thanks!
