### ISSUE TITLE
parameter -cpu vs real number of used cpu

### ISSUE THREAD

**Issue by BagiM** [clemgoub/dnaPipeTE#34]
Hello,

I am trying to run dnaPipeTE on university computing cluster. To run a job there I need to specify the number of cpu the job will use. If the job exceeds the specified cpu at any time-point it gets killed. 
I have found that if I use dnaPipeTE parameter -cpu exactly the same as number as specified cpus for job then the job gets killed at Trinity stage. I tried to add some buffer cpus for the job with several trials and killed jobs. I am currently at the iteration when if I use dnaPipeTE -cpu 6 and allocate 10 cpus for the job then the job gets killed at RepeatMasker stage, because apparently RepeatMasker tries to use more than 10 cpus.
Any suggestions on how to estimate real number of used cpus?

Thanks,
Markéta

**Comment by BagiM** [comment]
Hello,

I have found the coulprit for my problem here:

https://hpc.nih.gov/apps/repeatmasker.html

> By default, RepeatMasker will start 2 threads for every CPU in the node resulting in badly overloaded jobs. Users must prevent this behavior by setting -pa N where N is equal to the number of allocated CPUs divided by 2. In -pa N, "N" must always be greater than or equal to 2; -pa 1 causes RepeatMasker to run as though the -pa option was not specified and to start 2 threads for each CPU.

The problem seems to be dnaPipeTE.py script is calling RepeatMasker with parameter -cpu N simply passed as -pa N. This leads to RepeatMasker using twice as much resources then expected. 

Markéta

**Comment by clemgoub** [comment]
Sorry for the late reply, I actual remember your question and I thought I had replied.

Yes, I know this bug. We had fixed it in a earlier version, but we had to update RepeatMasker and did not change the code again. I will push soon a fix in the dnaPipeTE script to work this around.
Please ask me again if I haven't pushed a fix soon.

Cheers,

Clément
