### ISSUE TITLE
Issues installing on a cluster/HPC

### ISSUE THREAD

**Issue by tomh1lll** [clemgoub/dnaPipeTE#35]
Hi, I use dnaPipeTE frequently and it's great. I would like to get it working on my universities cluster but require some changes which I cannot work out. Specifically, my cluster has repeatmasker and trinity already installed in a module loading system, so I cannot install them again, but can use the preinstalled copies. How do I change dnaPipeTE to use Trinity and RepeatMasker that are already in the environment/path (as in I can use Trinity by just typing `Trinity` ) ?

Any help would be great.

Thanks

**Comment by clemgoub** [comment]
Hi Tom,

Thanks a lot for your message. I think we can tweak the code so it runs on your cluster. I need to look in the code again because there is a parameters file that override the paths when dnaPipeTE start. 
Can you send me the list of programs that you need to load as well as the command you use on your cluster to load them?

Thanks,

Clément

PS: a docker version of dnaPipeTE is in the works, I hope before the end of the year. This would make dnaPipeTE portable to virtually any machine.

**Comment by tomh1lll** [comment]
Hi Clement


Thanks for the speedy reply.

for my cluster I have to load preinstalled packages of interest using a command such as:


module load Trinity


Which I can do before I run dnaPipeTE, so that doesn't need to be part of the program.

Then I can use Trinity as if it was installed in the path, so don't need to put a directory to lead to it. As far as I'm aware, the preinstalled packages are Trinity, Repeatmasker (and I assume by extension, TRF), blast (as blast+, but can still call blastn and blastp), java/1.8.0_212, python3, perl, R

I'm not sure about GNU parallel but pretty certain it's not loaded.


Hopefully this is helpful, a docker version does sound cool!


Thanks so much for the help and the reply


Regards


Tom

________________________________

**Comment by clemgoub** [comment]
Hey Tom,

I understand. So, if you load the modules in your path, you can modify the file `congif.ini`. It contains the defaults arguments for dnaPipeTE and the path to the  programs. It is generated automatically if none is present and is overridden by the arguments passed to dnaPipeTE:

```
[DEFAULT]
repeatmasker = bin/RepeatMasker/RepeatMasker
trinity_glue = 1
blast_folder = bin/ncbi-blast-2.2.28+/bin/
sample_number = 2
sample_size = 500000
trinity_memory = 10G
trf = bin/trf
trinity = bin/trinityrnaseq-Trinity-v2.4.0/Trinity
repeatmasker_library =
parallel = bin/parallel
rm_species = All
````

So I guess if you change the path to only the binary/program names as called in your path, this should do the trick! Please let me know if other issues show up.

Cheers,

Clément
