### ISSUE TITLE
Figuring out how are Counts.txt calculated

### ISSUE THREAD

**Issue by BagiM** [clemgoub/dnaPipeTE#36]
Hello,

I am trying to understand dnaPipeTE outputs. Specifically I am trying to figure out how are the numbers in Counts.txt calculated. When I look into reads_per_component_and_annotation file and simply the numbers in the second (base pairs) column for the relevantly annotated rows I cant seem to arrive at the same number as dnaPipeTE.
For example in Counts.txt i find
Simple_repeat	34570800
However if I add all rows in assigned as Simple_repeat in reads_per_component_and_annotation I get:
Simple_repeat 10408258

Similarly in Counts.txt i have:
LTR	376818

But when looking into reads_per_component_and_annotation and adding all rows with "LTR" anotation I get:
LTR   149042

Is there some normalization involved?

The reason why I am asking this is because I will probably need to manually annotate some un-annotated and mis-annotated contigs, so i would like to know what are the next steps in the pipeline once I am done with reannotating.

Thanks,
Markéta

**Comment by clemgoub** [comment]
Hello Markéta,

I is a normal behavior of dnaPipeTE. Indeed, there is two type of quantification in dnaPipeTE:

1- direct quantification by mapping one sample of reads on the dnaPipeTE contigs ("Trinity.fasta")
- results in "reads_per_component_and_annotation" (+ annotation of the contig per RepeatMasker)
- graph: barplot
- Answer for: "what proportion of the genome each repeat represent?"

2- In a second, independent process, we then estimation of the TE content by considering a consensus "annotated" if it receive a RepeatMasker hit covering > RM_t of its sequence. We then quantify with 2 successive blasts: 1) against annotated assembled repeat (+ repbase consensus in case we did not assembled some low copy TE); 2) the unmapped reads in (from 1) are mapped against the non-annotated dnaPipeTE contigs. Then, the still unmapped read are assigned to "non-repetitive" 
- These results are in "Count.txt"
- Piechart
- Answer for "how many bp/%genome can be attributed to a given repeat class (LTR, LINE, SINE, DNA, MITE,...)"

The raw numbers (reads or bp) are at the end different between analysis to another, but only the proportions matter at the end. They are still expected to be different as the second analysis is more an estimation than a raw quantification. The first did not intend to quantify the TE but rather report the raw annotation given by repeat masker. In the second analysis, we take an annotation centered quantification, which include a precise attribution of the basepair.

Please let me know if you need further details or if you observe large differences between the ratios (in particular total repeat content as estimated by each method; it can be seen at a glance comparing the bar and pie charts).

**Comment by BagiM** [comment]
Oh, thanks for the clarification. It makes much more sense to me now.
My charts are a bit messed up right now since I used some old Repbase library for annotation and it did not go well with dnaPipeTE grouping into repeat classes. All of my Copia and Gypsy elements seem to be sorted into "other" category instead of "LTR". This does not bother me much since I was mostly interested in individual repeat families portion of genome, not overall class estimations.
Anyhow, the proportions in the bar-chart and pie-chart however funky seem to roughly agree.

May I ask you where do I find a total to which I should compare numbers in reads_per_component_and_annotation to get genome percentages? Surely, if I add all the lines I should get only total of mapped reads/base-paires, which excludes unmapped reads/base-pairs from single copy genes?

Many thanks,
Markéta

**Comment by clemgoub** [comment]
Hello Markéta!

Indeed, here's where you can find the info you are looking for:

- "reads_per_component_and_annotatios" --> the total reads used for this quantification are in the file "renamed.blasting_reads" and you can access the total # bp with this command:
```
awk 'NR%2 == 0 {basenumber += length($0)} END {print basenumber}' renamed.blasting_reads
```

- "Counts.txt" (pieChart) --> the total bp is the last line "Total"

Please let me know if you find inconsistencies, there may be some hidden twists in there after 6 years... =)

Cheers,

Clément

**Comment by dlata** [comment]
> Hello,
> 
> I am trying to understand dnaPipeTE outputs. Specifically I am trying to figure out how are the numbers in Counts.txt calculated. When I look into reads_per_component_and_annotation file and simply the numbers in the second (base pairs) column for the relevantly annotated rows I cant seem to arrive at the same number as dnaPipeTE.
> For example in Counts.txt i find
> Simple_repeat 34570800
> However if I add all rows in assigned as Simple_repeat in reads_per_component_and_annotation I get:
> Simple_repeat 10408258
> 
> Similarly in Counts.txt i have:
> LTR 376818
> 
> But when looking into reads_per_component_and_annotation and adding all rows with "LTR" anotation I get:
> LTR 149042
> 
> Is there some normalization involved?
> 
> The reason why I am asking this is because I will probably need to manually annotate some un-annotated and mis-annotated contigs, so i would like to know what are the next steps in the pipeline once I am done with reannotating.
> 
> Thanks,
> Markéta



> Hello,
> 
> I am trying to understand dnaPipeTE outputs. Specifically I am trying to figure out how are the numbers in Counts.txt calculated. When I look into reads_per_component_and_annotation file and simply the numbers in the second (base pairs) column for the relevantly annotated rows I cant seem to arrive at the same number as dnaPipeTE.
> For example in Counts.txt i find
> Simple_repeat 34570800
> However if I add all rows in assigned as Simple_repeat in reads_per_component_and_annotation I get:
> Simple_repeat 10408258
> 
> Similarly in Counts.txt i have:
> LTR 376818
> 
> But when looking into reads_per_component_and_annotation and adding all rows with "LTR" anotation I get:
> LTR 149042
> 
> Is there some normalization involved?
> 
> The reason why I am asking this is because I will probably need to manually annotate some un-annotated and mis-annotated contigs, so i would like to know what are the next steps in the pipeline once I am done with reannotating.
> 
> Thanks,
> Markéta

**Comment by dlata** [comment]
Hello @BagiM 

I am also using dnaPipeTe . I have annotated some of un-annotated contigs (Unannotated contigs were obtained from file unannotated.fasta in the Annotation Folder of dnaPipeTe) , and now after annotating these un-annotated contigs, I am interested in quantifying the percentage of repeat elements in the genome. 

1) If I understood the conversation correctly, One you manually annotated some un-annotated and mis-annotated contigs, In  order to quantify the repeat element percentage in genome (like LINE, SINE, LTR, etc) you used the file **reads_per_component_and_annotation**  as the second (base pairs) column of this file has information of base-pair relevant to repeat elements. And total number base pair was is present in Count.txt, that we can use. Is it correct ???
 
2) The reads_per_component_and_annotation has the raw quantification information whereas the Count.txt is more an estimation. As mentioned above that: "In the second analysis (Count.txt), we take an annotation centered quantification, which include a precise attribution of the base pair" than how idle it is to use reads_per_component_and_annotation file for quantifying repeats elements.?

Thanking you in advance for help.

**Comment by dlata** [comment]
Hello @clemgoub 

Luckily, I got to  find this issue in git-hub page, which is kind of similar what I am doing using dnaPipeTe.

If I understood the conversation correctly, Once you manually annotated some un-annotated and mis-annotated contigs, In order to quantify the repeat element percentage in genome (like LINE, SINE, LTR, etc) you used the file reads_per_component_and_annotation as the second (base pairs) column of this file has information of base-pair relevant to repeat elements. And total number base pair was is present in Count.txt, that we can use. Is it correct ??? (ex: for LTR family :Total base pair of Repeat family LTR/ Total base pairs). So this will give raw quantification of repeat family. One can use this approach to quantify the repeat elements proportion in the genome( as we have the information of the repeat family in this file)

The reads_per_component_and_annotation has the raw quantification information whereas the Count.txt is more an estimation based on annotation thresholds. As mentioned above that: "In the second analysis (Count.txt), we take an annotation centered quantification, which include a precise attribution of the base pair".
Than how idle or I should say precise results we will get using reads_per_component_and_annotation file for quantifying repeats elements.? As the number in both the file differ (based on approach used for analysis)

Thanking you in advance.

Thanks 
Dimpal

**Comment by clemgoub** [comment]
Hello,

>If I understood the conversation correctly, Once you manually annotated some un-annotated and mis-annotated contigs, In order to quantify the repeat element percentage in genome (like LINE, SINE, LTR, etc) you used the file reads_per_component_and_annotation as the second (base pairs) column of this file has information of base-pair relevant to repeat elements. And total number base pair was is present in Count.txt, that we can use. Is it correct ??? (ex: for LTR family :Total base pair of Repeat family LTR/ Total base pairs). So this will give raw quantification of repeat family. One can use this approach to quantify the repeat elements proportion in the genome( as we have the information of the repeat family in this file)

To normalize the counts of "read_per_component_and_annotation" you can access the total number of reads, and sum the total bp of reads using the file `renamed.blasting_reads`. 
`Count.txt` are estimations and cannot be used with the raw `read_per_component...`

> The reads_per_component_and_annotation has the raw quantification information (That is clear) whereas the Count.txt is more an estimation based on annotation thresholds( the threshold which we set using RM_t). In that case Count.txt should have take in account less reads (because of the threshold setting), but In many case I found it has more reads. Is it because it is matching reads to both contig and rep base I guess.

Indeed, Count.txt maps over two merged datasets: 1) the annotated dnaPipeTE contigs and 2) Repbase (to eventually map reads from non- or mis- assembled repeats; usually those with low copy number). So in fine, more reads are expected to map in `Counts.txt` than `reads_per_...`. However, the initial samples are the same (`renamed.blasting_reads`). The threshold simply split differently "annotated" from "unannotated" but the total number of dnaPipeTE sequences are the same (`Trinity.fasta`) at the end of the mapping.

>As mentioned above that: "In the second analysis (Count.txt), we take an annotation centered quantification, which include a precise attribution of the base pair".
Than how idle or I should say precise results we will get using reads_per_component_and_annotation file for quantifying repeats elements.? As the number in both the file differ (based on approach used for analysis)

This depends of your goal. If you want a precise comparison or the repeated content, regardless of the type or repeat, I suggest to use the results from `reads_per_...` as this are raw quantification of Trinity.fasta. However if your goal is to compare the TE diversity and distribution, I'd stick with the estimates of Counts.txt (and the pieChard), as well as the landscape graph.

Here a recent paper with a detailed downstream procedure for dnaPipeTE: https://www.mdpi.com/2073-4425/11/2/170

>-Lastly which file contains blast sample of repeats which is used for analysis of count.txt and reads_per_component_and_annotation? I guess "renamed.blasting_reads.fasta" has reads for reads_per_component_and_annotation but what about Count.txt??

Both quantification uses the same query reads found in `renamed.blasting_reads` or the raw sample file `s0_*.fastq_blast.fasta`. The other files, such as `s0*fastq.fasta` and `s1*fastq.fasta` are the samples taken before, for the different Trinity iterations. There is always as much files as there is iterations + `s0_*.fastq_blast.fasta` for the sampling (non-related to the s0 sample for Trinity).

Hope this answers help,

Best,

Clément

**Comment by dlata** [comment]
Hello @clemgoub,

Thanks, for reply. It was indeed helpful. Most of the queries were resolved. 

Though one thing to confirm:
In the paper "Homology-Free Detection of Transposable Elements Unveils Their Dynamics in Three Ecologically Distinct Rhodnius Species" (the link you attached) , In order to compare TE family (LTR,DNA,LINE, SINE, etc) between species they did use the  “read_per_component_and_annotation” file generated by dnaPipeTE in each species. As in the result part even they mentioned "The three species have similar proportions of TE-derived reads in their genomes: with 19% (R. prolixus1), 23.5% (R. montenegrensis),and 21.2% (R. marabaensis) **of the sampled reads mapping to the assembled TE contigs** .  I hope I got it right using "read_per_component_and_annotation" we can compare TE family proportion between species??

-Based on one's goal "of comparing the TE family(LTR,DNA,LINE, SINE, etc) proportion between species to see whats makes them different", one can use read_per_component_and_annotation file. And as well as later look into Landscape chart to see divergence. (Correct me if I am wrong)

-Even with "read_per_component_and_annotation" file one can get information of repeat family/class, than why did you mention"If you want a precise comparison or the repeated content, **regardless of the type or repeat**" . As this file do mention type of annotation (like #LTR/copia)

**Comment by clemgoub** [comment]
Hello,

Sorry for the late reply. You may find the new utilities [`dnaPT_utils`](https://github.com/clemgoub/dnaPT_utils) useful for this analysis. Please let me know if you need further assistance by re-opening this issue.

Best,

Clément
