### ISSUE TITLE
Figuring out read_per_component_and_annotation/bar_graph and Count.txt

### ISSUE THREAD

**Issue by aryakumar563** [clemgoub/dnaPipeTE#37]
Hello,

I am trying to figure out the output of dnaPipeTE. 
What does the bar plot obtained from the read_per_component_and_annotation represents. what does rep >0.1 applies ? Does it signify something with contig assembled.
Do we have a file with base pair mapped from which analysis of Count.txt is done. I am aware that read_per_component_and_annotation have information of read_mapped, bp_mapped. But these numbers are different from Count.txt file. So, I was wondering if there is some file which is used from which we get the Count.txt analysis done.
Lastly, can we get access to file which had all reads which where used for blastn search.

**Comment by clemgoub** [comment]
Dear @aryakumar563,

Sorry for the delays, somehow I missed the notification for your issue.

_What does the bar plot obtained from the read_per_component_and_annotation represents. what does rep >0.1 applies ? Does it signify something with contig assembled._

- It indicates the most repeated dnaPipeTE contigs, reaching  >0.1% of the genome.

_Do we have a file with base pair mapped from which analysis of Count.txt is done. I am aware that read_per_component_and_annotation have information of read_mapped, bp_mapped. But these numbers are different from Count.txt file. So, I was wondering if there is some file which is used from which we get the Count.txt analysis done._

- Indeed, the number are different: Count.txt is the result of successive blastn against 1) annotated repeats, then 2) unannotated repeats and finaly unmapped are considered non-repetitive. `read_per_component_and_annotation` is made directly counting the reads against `Trinity.fasta`. To dive in the details of `Count.txt`, a custom python script `blast_sorter.py` analyzes the file `./blast_out/int.reads_vs_annoted.blast.out` to produce `./blast_out/s.reads_vs_annoted.blast.out ` which can be of use for you.

_Lastly, can we get access to file which had all reads which where used for blastn search._

- yes, this is `renamed.blasting_reads.fasta`

Cheers, and sorry for the delay again...

Clém
