### ISSUE TITLE
RepeatMasker checkpoint never triggers as RepeatMasker done

### ISSUE THREAD

**Issue by BagiM** [clemgoub/dnaPipeTE#38]
Hello,
I have run dnaPipeTE on university cluster which has access to RepeatMasker library. The analysis did get past the RepeatMasker step but and failed to produce graphs. I wanted to rerun the last part on my computer where I know the graphs do get produced but I only have there an old RepeatMasker library. The dnaPipeTE does successfully skip Trinity phase but always reruns RepeatMasker.

Is suspect the problem is the test_RepeatMasker checks for presence of file /Annotation/Best_RM_annot_80_80 which seems to be never produced. Shouldn't it be checking for /Annotation/Best_RM_annot_80 instead? Or did something wrong happen with my run and /Annotation/Best_RM_annot_80_80 should be there?

**Comment by clemgoub** [comment]
Hello BagiM,

It is a bug in the checkpoints script. I am aware of it, and this is on the current list of fixes for the next release.

In the meantime, here are the commands so you can directly generate the graphs. Run them directly from the dnaPipeTE source folder. The files in arguments are in your designated dnaPipeTE output folder.

`Rscript graph.R Reads_to_components_Rtable.txt blast_reads.counts` --> barplot contig quantification (direct contig quantification)
`Rscript pieChart.R Counts.txt pieColors` --> piechart (Subclass % estimates)
`Rscript landscapes.R reads_landscape factors_and_colors blast_reads.counts` --> TE landscape (ages)

Hope it helps!

Cheers,

Clément
