### ISSUE TITLE
Pacbio reads ?

### ISSUE THREAD

**Issue by ptranvan** [clemgoub/dnaPipeTE#4]
Hi,

I am wondering if dnaPipeTE works with pacbio read ?

**Comment by clemgoub** [comment]
Hi ptranvan,

It has not been designed to work with PacBio reads. Most of the pipeline rely on Trinity and Blastn for short reads and dnaPipeTE has been optimized with reads that ranges so far 100-300bp. However I'll be happy to hear from your feedback if you'll give a try!.

Clément
