### ISSUE TITLE
missing 'reads_per_component_and_annotation' in output folder

### ISSUE THREAD

**Issue by avahaley** [clemgoub/dnaPipeTE#40]
Hello!

I have run dnaPipeTE on a few different species, most of them around 0.1x coverage. My outputs include everything that should be there, except for the reads_per_component_and_annotation file, and the graphs. The graphs are to be expected as I am running from a supercomputer cluster without R. Do I need R for the reads_per_component_and_annotation file to generate as well? 
Is it safe to just use the Counts.txt file to determine the percentage of a TE class in the genome? Is there a way to determine superfamily annotations without this file? 

Hopefully this makes sense, I am very new to this. Thank you!

**Comment by clemgoub** [comment]
Hey!

You need R indeed. There is a few calculations and sorting done with it, as well as all the graphs. Sorry!

Best,

Clément
