### ISSUE TITLE
About input file

### ISSUE THREAD

**Issue by zhang144999** [clemgoub/dnaPipeTE#43]
Dear dnaPipeTE developer
I'm confused about the input option.
Now I have paired end file, but the dnaPipeTE is only hand single end only.
I dont know I just put the one end or reverse the reverse file and merge the forward file.
So would you mind give me some advise for me?
Thanks 
yours Zhang

**Comment by clemgoub** [comment]
Hello,

The simplest is that you either use the R1 or R2 read file only. Either one will work.
There is no need for paired-end in dnaPipeTE, so you are not loosing information by using one end of a paired-end read set.

Best,

Clément
