### ISSUE TITLE
Installation issue in Linux Redhat 6.2

### ISSUE THREAD

**Issue by nishmadahal** [clemgoub/dnaPipeTE#45]
I have been trying to install dnaPipeTE on Linux server (version 6.2, Redhat). After adding the login and password in the file (init.sh) I tried to run it as suggested in the installation, I get the following message. 

[nishma@login1 dnaPipeTE]$ ./init.sh
GIRINST_USERNAME=******: Command not found.
GIRINST_PASSWORD=******: Command not found.
GIRINST_USERNAME: Undefined variable.

The same username and password had worked on a Linux computer, the RAM is small so I could not run the analyses on the computer.

**Comment by clemgoub** [comment]
Dear Nishmadahal,

I have never tried dnaPipeTE on a RedHat server, but maybe you can try to change the way the variable with you ID is passed:
Try remove the quotes before and after name/pwd in the init.sh -- or change the simple quotes by double quotes

Let me know if there is no change after that. Did you check that your login information are still working on the [repbase website](https://www.girinst.org/login.html?partnerId=repbase&redirect=https%3A%2F%2Fwww.girinst.org%2Faccountservices%2F)? 

Let me know!

Best,

Clément

**Comment by clemgoub** [comment]
Closing this issue since it concerns the non-container version. Please DM if further support is needed. Thank you!
