### ISSUE TITLE
RepeatMasker libraries not found

### ISSUE THREAD

**Issue by caroliog** [clemgoub/dnaPipeTE#46]
Hi!

I'm attempting to install your program, but when configuring RepeatMasker it doesn't seem to find the required libraries. I'm pointing to a path that should contain them, but I get this error message:

```
No repeat libraries found!  At a minimum the Dfam_consensus
is required to run.  Please download and install the latest 
Dfam_consensus.  It is highly recommended that you also install the
latest RepBase RepeatMasker Edition library obtainable from GIRI.
General instructions can be found here: http://www.repeatmasker.org
```
The folder does have a file called `DfamConsensus.embl`, but is this not what it is looking for?

Thanks so much for any help!

Caroline

**Comment by clemgoub** [comment]
Hi Caroline,

Can you tell me exactly which path you are giving RepeatMasker for the libraries? Normally, the directory to point to is dnaPipeTE/bin/RepeatMasker/Libraries 
To double check, follow the instruction to install the RM libraries here: http://repeatmasker.org/RepeatMasker/
update the DFAM library as indicated:

```
wget https://www.dfam.org/releases/Dfam_3.2/families/Dfam.h5.gz
gunzip Dfam.h5.gz
mv Dfam.h5 <installpath>/dnaPipeTE/bin/RepeatMasker/Libraries
cd <installpath>/dnaPipeTE/bin/RepeatMasker/
./configure
```

Please let me know if the libraries are still not working, I will find another solution!

Cheers,

Clément

**Comment by caroliog** [comment]
Hi, 

Thank you for responding!

I’ve updated the the DFAM library as indicated, but running ./test_config.sh still tells me 

`RepeatMasker.lib doesn't include the Repbase sequences!`

The path I give for RepeatMasker is 
`/proj/sllstore2017073/private/Caroline/dnaPipeTE/bin/RepeatMasker `
(where `/proj/sllstore2017073/private/Caroline` is my work directory)
during the configuration process I am never actually asked specifically for the path to the libraries, but I'm assuming it looks in `/proj/sllstore2017073/private/Caroline/dnaPipeTE/bin/RepeatMasker/Libraries/` where Dfam.h5 is located. 

Caroline

**Comment by clemgoub** [comment]
Hello Caroline,

I think it can still works. The test script only look for Repbase libraries, but these DFAM should work just as well with dnaPipeTE. I suggest you to do the test run as indicated in the GitHub, regardless this error message.

Let me know if you have results, and you can send me the full log and command line if it doesn't go through.

Best,

Clément

**Comment by nishmadahal** [comment]
Hello,

I ran ./init.sh 
Now I am supposed to find "cd bin/RepeatMasker" and run "./configure"

But, i only have directory named "parallel" inside bin

I found RepBaseRepeatMaskerEdition-20170127.tar.gz outside bin, but it cannot be unzipped. 

2021-02-25 15:29:32 (18.8 MB/s) - ‘RepBaseRepeatMaskerEdition-20170127.tar.gz.2’ saved [9661/9661]

mv: cannot move 'RepBaseRepeatMaskerEdition-20170127.tar.gz' to 'RepeatMasker/': Not a directory
./init.sh: line 69: cd: RepeatMasker: No such file or directory

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by clemgoub** [comment]
Hello, 

It seems that the download and extraction or RepeatMasker (step before) did not work.
I tried this morning and the RepeatMasker folder should be in ./bin after running the script.

I advise you to try manually from within the dnaPipeTE folder:

```
cd bin/
curl -k -L http://repeatmasker.org/RepeatMasker-open-4-0-7.tar.gz -o RepeatMasker-open-4-0-7.tar.gz
tar -zxvf RepeatMasker-open-4-0-7.tar.gz
```

after that, your Repbase library seems to have an extra ".2" at the end. Simply

```
mv RepBaseRepeatMaskerEdition-20170127.tar.gz.2 bin/RepeatMasker/RepBaseRepeatMaskerEdition-20170127.tar.gz
cd bin/RepeatMasker
tar -zxvf RepBaseRepeatMaskerEdition-20170127.tar.gz
```

now you can run `./configure` to finalize RepeatMasker installation
I assume that you have a Repbase subscription. If not, follow the instruction to use the DFAM libraries as indicated here: http://www.repeatmasker.org/RepeatMasker/

Let me know how it works for you, and please let me know if you need further help!

Cheers,

Clément

**Comment by nishmadahal** [comment]
Thanks, for prompt response.

Looks like RepeatMasker-open-4-0-7.tar.gz is not a gzip file. *So, how do I
unzip it? *
gzip -v -t RepeatMasker-open-4-0-7.tar.gz

gzip: RepeatMasker-open-4-0-7.tar.gz: not in gzip format

Also, I have my profile on Repbase (whose user id and password I provided
in "init.sh" ), but I do not have a subscription. I was also struggling to
find  DFAm libraries. Thanks for your help.

Many thanks
Nishma Dahal
DST- INSPIRE faculty & Asst. Professor (AcSIR),
Department of Biotechnology,
CSIR-Institute of Himalayan Bioresource Technology,
Palampur-176061 (HP)

**Comment by clemgoub** [comment]
To unzip it, you need to use the tar+gzip command

```
tar -zxvf RepeatMasker-open-4-0-7.tar.gz
```

Cheers,

Clément

**Comment by nishmadahal** [comment]
Somehow thats not working. It gives me following error
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now


Nishma Dahal
DST- INSPIRE faculty & Asst. Professor (AcSIR),
Department of Biotechnology,
CSIR-Institute of Himalayan Bioresource Technology,
Palampur-176061 (HP)

**Comment by clemgoub** [comment]
Ho, then it could be that the downloaded file is corrupted.

You can try the following:

`cd` in the `dnaPipTE/bin` directory
```sh
wget http://www.repeatmasker.org/RepeatMasker/RepeatMasker-4.1.1.tar.gz
gunzip RepeatMasker-4.1.1.tar.gz
tar xvf RepeatMasker-4.1.1.tar
```

This should download and unpack the latest RepeatMasker version.
The next step is to configure it:
```
cd ./RepeatMasker
./configure
```
```
Enter path [ /usr/local/bin/perl ]:
```
Just press enter. The path should be found automatically.
```
Enter path [ /yourpath/dnaPipeTE/bin/RepeatMasker ]:
```
Same thing here, the path to RepeatMasker should be found automatically.
```
Enter path [ ]: </yourpath>/dnaPipeTE/bin/trf
```
Here, replace by the path to the dnaPipeTE folder. The default prompt should be empty, unless you already have trf in your path.
```
Add a Search Engine:
   1. CrossMatch: [ Un-configured ]
   2. RMBlast - NCBI Blast with RepeatMasker extensions: [ Un-configured ]
   3. WUBlast/ABBlast (required by DupMasker): [ Un-configured ]
   4. HMMER3.1 & DFAM: [ Un-configured ]

   5. Done

Enter Selection: 2
```
Choose 2 and press enter

```
**RMBlast (rmblastn) INSTALLATION PATH**
```
This is the path to the location wherethe rmblastn and makeblastdb programs can be found.

```
Enter path [  ]: </yourpath>/dnaPipeTE/bin/ncbi-blast-2.2.28+/bin  
```
Same thing here, replace with the path to your local installation of dnaPipeTE. Then press enter. Be carefull to not add a final / after the 'bin', for some reason it is very sensitive!
```
Do you want RMBlast to be your default
search engine for Repeatmasker? (Y/N)  [ Y ]:Y
```
Choose `Y` and press enter.

```
Add a Search Engine:
   1. CrossMatch: [ Un-configured ]
   2. RMBlast - NCBI Blast with RepeatMasker extensions: [ Configured, Default ]
   3. WUBlast/ABBlast (required by DupMasker): [ Un-configured ]
   4. HMMER3.1 & DFAM: [ Un-configured ]

   5. Done


Enter Selection: 5
```
Choose 5 here and press enter.

This should install RepeatMasker and build the default libraries (DFAM). Let me know if you need further assistance!

Best,

Clément

**Comment by nishmadahal** [comment]
Hi sorry again I am stuck. I downloaded it manually (coz institute's
internet was blocking it when I used wget) and unzipped repeatmasker, then
gunzip and tar xvf worked.
 I am now trying to configure, I entered perl path.









*I am stuck after this; This is what I get after I put dnaPipe folder
The full path including the name for the TRF program.TRF_PRGM:
/home/user/Downloads/dnaPipeTE-masterThe value
"/home/user/Downloads/dnaPipeTE-master" appears to be a directory
ratherthan an executable binary or script!<PRESS ENTER TO CONTINUE,
CTRL-C TO BREAK>*

*Inside my dnaPipe folder I have the following;*

user@user:~/Downloads/dnaPipeTE-master/bin/RepeatMasker$ ls
addRepBase.pl              INSTALL                    RepeatMaskerConfig.pm
ArrayListIterator.pm       Libraries                  repeatmasker.help
ArrayList.pm               LibraryUtils.pm            RepeatProteinMask
bluegrad.jpg               LICENSE                    RepeatRecord.pm
configure                  Matrices                   SearchEngineI.pm
CrossmatchSearchEngine.pm  Matrix.pm                  SearchResultCollection.pm
DateRepeats                NCBIBlastSearchEngine.pm   SearchResult.pm
daterepeats.help           NCBIBlastXSearchEngine.pm  SeqDBI.pm
DFAM.pm                    ProcessRepeats             SimpleBatcher.pm
DFAMRecord.pm              PRSearchResult.pm          Taxonomy.pm
DupMasker                  PubRef.pm                  TRF.pm
EMBL.pm                    README.md                  TRFResult.pm
famdb.py                   ReleaseNotes               TRFSearchResult.pm
FastaDB.pm                 RepbaseEMBL.pm             util
HMMERSearchEngine.pm       RepbaseRecord.pm           WUBlastSearchEngine.pm
HTMLAnnotHeader.html       RepeatMasker               WUBlastXSearchEngine.pm

Here, replace by the path to the dnaPipeTE folder. The default prompt
should be empty, unless you already have trf in your path.

Add a Search Engine:

   1. CrossMatch: [ Un-configured ]

   2. RMBlast - NCBI Blast with RepeatMasker extensions: [ Un-configured ]

   3. WUBlast/ABBlast (required by DupMasker): [ Un-configured ]

   4. HMMER3.1 & DFAM: [ Un-configured ]



   5. Done



Enter Selection: 2


Choose 2 and press enter

**RMBlast (rmblastn) INSTALLATION PATH**


This is the path to the location wherethe rmblastn and makeblastdb programs
can be found.

Enter path [  ]: </yourpath>/dnaPipeTE/bin/ncbi-blast-2.2.28+/bin


Same thing here, replace with the path to your local installation of
dnaPipeTE. Then press enter. Be carefull to not add a final / after the
'bin', for some reason it is very sensitive!

Do you want RMBlast to be your default

search engine for Repeatmasker? (Y/N)  [ Y ]:Y


Choose Y and press enter.

Add a Search Engine:

   1. CrossMatch: [ Un-configured ]

   2. RMBlast - NCBI Blast with RepeatMasker extensions: [ Configured, Default ]

   3. WUBlast/ABBlast (required by DupMasker): [ Un-configured ]

   4. HMMER3.1 & DFAM: [ Un-configured ]



   5. Done





Enter Selection: 5


Choose 5 here and press enter.

This should install RepeatMasker and build the default libraries (DFAM).

Nishma Dahal
DST- INSPIRE faculty & Asst. Professor (AcSIR),
Department of Biotechnology,
CSIR-Institute of Himalayan Bioresource Technology,
Palampur-176061 (HP)

**Comment by nishmadahal** [comment]
Hello again

We have tried to resolve some of the basic issues and finally reached the
step to run the test script provided. Please find attached the log of the
error.

Many thanks
Nishma Dahal
DST- INSPIRE faculty & Asst. Professor (AcSIR),
Department of Biotechnology,
CSIR-Institute of Himalayan Bioresource Technology,
Palampur-176061 (HP)

**Comment by clemgoub** [comment]
Hi Nishma,

I'm sorry I didn't get the log file!

Clément

**Comment by nishmadahal** [comment]
Hi

The error message I get is (also attached),

----------- Jellyfish  --------------------
-- (building a k-mer catalog from reads) --
-------------------------------------------

CMD:
/home/user/Downloads/dnaPipeTE-master/bin/trinityrnaseq-Trinity-v2.5.1/util/..//trinity-plugins/jellyfish/bin/jellyfish
count -t 1 -m 25 -s 100000000  --canonical  single.fa
/home/user/Downloads/dnaPipeTE-master/bin/trinityrnaseq-Trinity-v2.5.1/util/..//trinity-plugins/jellyfish/bin/jellyfish:
error:
`/home/user/Downloads/dnaPipeTE-master/bin/trinityrnaseq-Trinity-v2.5.1/trinity-plugins/jellyfish/bin/.libs/jellyfish'
does not exist
This script is just a wrapper for jellyfish.
See the libtool documentation for more information.
Error, cmd:
/home/user/Downloads/dnaPipeTE-master/bin/trinityrnaseq-Trinity-v2.5.1/util/..//trinity-plugins/jellyfish/bin/jellyfish
count -t 1 -m 25 -s 100000000  --canonical  single.fa died with ret 256 at
/home/user/Downloads/dnaPipeTE-master/bin/trinityrnaseq-Trinity-v2.5.1/util/
insilico_read_normalization.pl line 758.
Error, cmd:
/home/user/Downloads/dnaPipeTE-master/bin/trinityrnaseq-Trinity-v2.5.1/util/
insilico_read_normalization.pl --seqType fa --JM 10G  --max_cov 50 --CPU 1
--output
/home/user/Downloads/dnaPipeTE-master/Test_output/Trinity_run2/insilico_read_normalization
  --max_pct_stdev 10000  --single
/home/user/Downloads/dnaPipeTE-master/Test_output/s1_test_dataset.fastq.fasta
died with ret 512 at
/home/user/Downloads/dnaPipeTE-master/bin/trinityrnaseq-Trinity-v2.5.1/Trinity
line 2544.
main::process_cmd("/home/user/Downloads/dnaPipeTE-master/bin/trinityrnaseq-Trini"...)
called at
/home/user/Downloads/dnaPipeTE-master/bin/trinityrnaseq-Trinity-v2.5.1/Trinity
line 3090
main::normalize("/home/user/Downloads/dnaPipeTE-master/Test_output/Trinity_run"...,
50, ARRAY(0x55f47c939e10)) called at
/home/user/Downloads/dnaPipeTE-master/bin/trinityrnaseq-Trinity-v2.5.1/Trinity
line 3037
main::run_normalization(50, ARRAY(0x55f47c939e10)) called at
/home/user/Downloads/dnaPipeTE-master/bin/trinityrnaseq-Trinity-v2.5.1/Trinity
line 1302
RepeatMasker version 4.1.1
Search Engine: NCBI/RMBLAST [ 2.10.0+ ]

Using Master RepeatMasker Database:
/home/user/Downloads/dnaPipeTE-master/bin/RepeatMasker/Libraries/RepeatMaskerLib.h5
  Title    : Dfam
  Version  : 3.2
  Date     : 2020-07-02
  Families : 6,953

Species/Taxa Search:
   [NCBI Taxonomy ID: ]

  0 families in ancestor taxa; 6953 lineage-specific families

Many thanks
Nishma Dahal
DST- INSPIRE faculty & Asst. Professor (AcSIR),
Department of Biotechnology,
CSIR-Institute of Himalayan Bioresource Technology,
Palampur-176061 (HP)

**Comment by clemgoub** [comment]
Hi Nishma,

It seems that the install of Trinity was incomplete, and Jellyfhish (count k-mers) is not installed. You can try to re-install Trinity

```
cd /home/user/Downloads/dnaPipeTE-master/bin
rm -r trinityrnaseq-Trinity-v2.5.1
curl -k -L https://github.com/trinityrnaseq/trinityrnaseq/archive/Trinity-v2.5.1.tar.gz -o Trinity-v2.5.1.tar.gz
tar -zxvf Trinity-v2.5.1.tar.gz
cd trinityrnaseq-Trinity-v2.5.1
make
``` 

Look for possible errors during the compilation, especially regarding Jellyfish, and let me know.
If the install goes without errors, you can try the test run of dnaPipeTE again.

Cheers,

Clément

**Comment by clemgoub** [comment]
Closing this issue since it concerns the non-container version. Please DM if further support is needed. Thank you!
