### ISSUE TITLE
trinity install as part of dnapipeTE

### ISSUE THREAD

**Issue by signor-molevol** [clemgoub/dnaPipeTE#49]
The code is ./init.sh

I'm getting the following error during the trinity install: 

g++  -W -Wall -Wno-unused -Wno-deprecated -ansi -pedantic -Wno-long-long -fno-nonansi-builtins -Wctor-dtor-privacy -Wsign-promo -Woverloaded-virtual -Wendif-labels  -O3  -ggdb3 -DMAKE_DATE='"Wed 17 Mar 2021 08:40:09 PM UTC  "' -DMAKE_OS_RELEASE='"5.3.0-64-generic"' -DMAKE_RELEASE='"3.0"' -DNEW_MAKEFILE -imacros system/BigFileDefines.h -pthread  -ftemplate-depth-30 -fno-strict-aliasing -mieee-fp   -fopenmp        -c ./aligns/KmerAlignCore.cc -o obj/aligns/KmerAlignCore.o
./aligns/KmerAlignCore.cc:6:10: fatal error: aligns/KmerAlignCore.h: No such file or directory
    6 | #include "aligns/KmerAlignCore.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:474: aligns/KmerAlignCore.o] Error 1

From what I can tell, and that is not a lot, this is perhaps related to newer versions of gcc being incompatible with something about this. I can get Trinity installed just fine in a conda environment, but can't figure out how to get dnaPipeTE to look for that instead of its own specific install. If you know either a) how to fix this error or b) how to make dnaPipeTE use a system install of Trinity (if it even can, I have no idea how dependent it is on that particular version of Trinity) I would appreciate it.

**Comment by clemgoub** [comment]
Hello!

I think we can find a workaround. Look in the dnaPipeTE folder for the file `config.ini`. If absent, run dnaPipeTE.py once; it will crash, but should create the config file. If this doesn't work, copy the following into a new file named `config.ini` in the dnaPipeTE folder.

```
repeatmasker = bin/RepeatMasker/RepeatMasker
trinity_glue = 1
blast_folder = bin/ncbi-blast-2.2.28+/bin/
sample_number = 2
sample_size = 500000
trinity_memory = 10G
trf = bin/trf
trinity = bin/trinityrnaseq-Trinity-v2.4.0/Trinity
repeatmasker_library =
parallel = bin/parallel
rm_species = All
```
Once you have the config file, change the path to your local installation of Trinity.
Activate the conda environment and try to do the [test run](https://github.com/clemgoub/dnaPipeTE#test-run) of dnaPipeTE

Let me know how this works!

Best,

Clément

**Comment by signor-molevol** [comment]
Thank you for getting back to me with a suggestion! I actually just found that adding this after line 380 of the makefile for Chrysalis worked, it was suggested as a fix when gcc was in version 6, now that its 9+ you just need an extra entry

ifeq ($(GPP_MAJOR_VERSION),9)
       SYS_INCS        = -iquote . $(XERCES_INC)
endif

**Comment by clemgoub** [comment]
Excellent, thank you for sharing!
