### ISSUE TITLE
Trinity.fasta is empty

### ISSUE THREAD

**Issue by buendiad** [clemgoub/dnaPipeTE#52]
Hello! :) 
Im trying to run the script having everything installed and cheked following the instructions. For now I am only working on the test to see if everything is ready for my own data. However, I am finding some difficulties, starting with Trinity not writing anything on the trinity.fasta.

This is my error message
[error.txt](https://github.com/clemgoub/dnaPipeTE/files/6420138/error.txt)

I'm running it on a cluster, with a conda environment python v3.6. Please, if you need more info, don't hesitate in contacting me :)

**Comment by clemgoub** [comment]
Hi there!

Thank you for using dnaPipeTE!

Looking at your log it seems that Trinity can't find the path to bowtie 2 executables. Depending on your system, you may want to locate and add bowtie 2 to your user path (using `export` or adding the path to your ~.bashrc or similar -- [see here](https://linuxize.com/post/how-to-add-directory-to-path-in-linux/)) or load bowtie 2 in the user environment (HPC-style clusters: `module load bowtie2`). Maybe [this thread](https://groups.google.com/g/trinityrnaseq-users/c/gLWCBXTeLyc) can help you further with this issue.

Given that this error occurred, I anticipate that you may encounter the same issue with `Jellyfish` which count k-mers at the beginning of Trinity. If that's the case, you can repeat the same fix to add Jellyfish executable in your path. It should be available with Trinity.

Please let me know if you need further help!

Cheers,

Clément

**Comment by buendiad** [comment]
Hi Clément!
I managed to solve the problem, I just had to load bowtie2 in my conda environment. That made it work :)

Thank you so much!

**Comment by clemgoub** [comment]
Fantastic!

Cheers,

Clément
