### ISSUE TITLE
Consolidating output from multiple runs

### ISSUE THREAD

**Issue by andreaswallberg** [clemgoub/dnaPipeTE#54]
Dear @clemgoub & Co,

I have completed 16 replicate runs of dnaPipeTE, subsampling about 0.08x of non-overlapping short-read data (I actually have 16 distinct sequence libraries and just grabbed the top 10M reads from each) from an organism with a very large genome. The results seem reasonable and I am looking for a suggested method to consolidate the output and make one "pan library" with reduced redundancy from the 16 independent runs.

What is the recommended method for doing so? Running CD-hit across the 16 replicates for each category at a time?
Are there any scripts around for repeat consolidation for dnaPipeTE?

**Comment by clemgoub** [comment]
Hello Andreas,

I'm very sorry I missed your issue. Indeed CD-HIT seems a good strategy. These parameters are my favorite (as they work well for TE)

```
cd-hit-est -i concatenated_replicates_Trinity.fasta -o non-redundant.fa -aS 0.8 -c 0.8 -G 0 -g 1 -b 500
```

Cheers, and again, sorry for the delais...

Clém
