### ISSUE TITLE
dnaPipeTE Runtime/Arguments

### ISSUE THREAD

**Issue by heidihyang** [clemgoub/dnaPipeTE#57]
Hello,

I have been trying to run dnaPipeTE on 1-6x coverage genomes of Tetragnatha spiders (~1 Gb) on a cluster, and the jobs keep timing out because they exceed the 3-day computing time limit. I currently have one job running on a longer runtime cluster (10-day time and 4 CPU per job limits) and it is still running after 8 days.
  
Regarding this,
Are these runtimes normal given the coverage and size of the genomes? If not, what recommendations do you have to shorten the runtime (multiple nodes, # CPUs)? I have tried one with 20 CPUs and it still timed out.
How many Trinity iterations are recommended, and without specifying this argument does the program optimize it?
Since the genomes have variable coverage, do you recommend normalizing the coverage (i.e. have all specimens with 1x or so)?
Would a lower genome coverage (0.2-0.5x) work well?

Thank you in advance!

**Comment by clemgoub** [comment]
Hi @heidihyang!

Thank you for using dnaPipeTE! 

The program is actually made to run with samples < 1X. You can run the program at 0.2-0.5X with no problem. It was developed using this coverage in the Asian tiger mosquito, which is 1-2Gbp. The sort commands (bash) are not memory friendly, so going over 1X can indeed stress the memory! 

Typically, a first run using 0.25X of reads and 2 Trinity iterations will give you a good estimate. In larger genomes, 0.1X is often sufficient to recapitulate the repeat fraction. Increasing the number of Trinity iterations can improve the assembly of repeats as it will enrich the total sample of reads in the assembly with repeat-derived reads, but won't have an extra cost on the memory as coverage does.

Let me know if you need more precision,

Best,

Clément

**Comment by heidihyang** [comment]
Hi Clément,

Thank you for your response! I ran some sequences using 0.25x genome coverage and 2 Trinity iterations and the runtime is much better. 

Best,
Heidi

**Comment by clemgoub** [comment]
Excellent! I'm glad to hear it! 
Cheers,
Clément
