### ISSUE TITLE
Repeat Landscape Plots Not Generated

### ISSUE THREAD

**Issue by heidihyang** [clemgoub/dnaPipeTE#58]
Hi Clément,

I've run all of my sequences but none of them have generated repeat landscape plots. Is there a way to run the landscapes.R script manually, and if so what arguments/files would be necessary? Thank you!

Best,
Heidi

**Comment by clemgoub** [comment]
Hi Heidi,

Yes this is possible. This graph requires ggplot2, which sometimes may not be present or loaded where dnaPipeTE runs.
You can generate the graphs with the following command:

```
Rscript ./landscapes.R reads_landscape factors_and_colors blast_reads.counts
```

- `landscapes.R` is located in the dnaPipeTE/ folder
- `reads_landscape`, `factors_and_colors` and `factors_and_colors` should be in your output folder.

Let me know if you need further help!

Cheers,

Clément

**Comment by heidihyang** [comment]
Hi Clément,

I've loaded the ggplot2 module but I'm getting this error:
```
Error in loadNamespace(name) : there is no package called 'labeling'
Calls: <Anonymous> ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```
I've looked for a package called labeling in my cluster's modules but I cannot find it. Do you know of a way around this? Thanks!

Best,
Heidi

**Comment by clemgoub** [comment]
Hi Heidi,

Can you tell me what server architecture is your cluster has? I had never encountered this error... It may be specific to your cluster. If you have a technical support team for it I would ask them about it.

An alternative can be to use the docker version of dnaPipeTE: https://hub.docker.com/r/clemgoub/dnapipete/

It has limited support right now but it is functional and will allow you to run dnaPipeTE without dependancies issues.

Best,

Clément

**Comment by heidihyang** [comment]
Hi Clément,

Here is the system overview of UC Berkeley's Savio cluster: https://docs-research-it.berkeley.edu/services/high-performance-computing/overview/system-overview/. And I will ask the IT team!

Thanks,
Heidi

**Comment by clemgoub** [comment]
Hi Heidi,

Thanks, this is very similar to mine, but I am not sure about the error you're getting.
You can try to make the graphs on your personal computer, as it only requires R and ggplot2 and should only take a second.

Let me know if your IT team suggests a fix or finds a solution, it will be valuable for this forum!

Thanks!

Clément

**Comment by clemgoub** [comment]
please see https://github.com/clemgoub/dnaPT_utils
