### ISSUE TITLE
FileNotFoundError in repeatmasker_run

### ISSUE THREAD

**Issue by rbpisupati** [clemgoub/dnaPipeTE#6]
Hi, 

In line 378, isnt Trinity fasta should be Trinity.fasta rather than Trinity.fasta.out?
with open(self.output_folder+"/Trinity.fasta.out", 'r') as trinity_handle

Thanks, 
Rahul

**Comment by clemgoub** [comment]
Hi Rahul,


I don't think so, because here we are parsing the RepeatMasker output of 
Trinity.fasta (the contigs) which is well Trinity.fasta.out


Cheers,

Clément

**Comment by clemgoub** [comment]
Can you give me more information about the error you have?

**Comment by rbpisupati** [comment]
Hi, 

here is the last lines from the log file of dnaPipe run

Trinity iteration 2 Done'
renaming Trinity output...
done
dna_SRR352164/Annotation/one_RM_hit_per_Trinity_contigs
dna_SRR352164/Annotation/Best_RM_annot_80-80
dna_SRR352164/Annotation/Best_RM_annot_partial
#######################################
### REPEATMASKER to anotate contigs ###
#######################################

Traceback (most recent call last):
  File "/home/GMI/rahul.pisupati/Softwares/dnaPipeTE/dnaPipeTE.py", line 700, in <module>
    RepeatMasker(config['DEFAULT']['RepeatMasker'], args.RepeatMasker_library, args.RM_species, args.cpu, args.output_folder, args.RM_threshold)
  File "/home/GMI/rahul.pisupati/Softwares/dnaPipeTE/dnaPipeTE.py", line 359, in __init__
    self.repeatmasker_run()
  File "/home/GMI/rahul.pisupati/Softwares/dnaPipeTE/dnaPipeTE.py", line 378, in repeatmasker_run
    with open(self.output_folder+"/Trinity.fasta.out", 'r') as trinity_handle:
FileNotFoundError: [Errno 2] No such file or directory: 'dna_SRR352164/Trinity.fasta.out'

**Comment by clemgoub** [comment]
Hi Rahul,

Can you send me the whole log, as well as your complete command line for the dnaPipeTE run? There is maybe different possible reason why RepeatMasker failed to produce the outfile, and the initial error may be upstream even though it did not stop the script. Also, for some reasons (that I don't know!) the log is not always outputted in perfect order, so it helps to have it in its complete version!

Thanks a lot,

Clément

**Comment by rotifergirl** [comment]
Hi, I am having a similar issue when running the test after installation

I ran 
`python dnaPipeTE.py -input test_dataset.fastq -output test -genome_size 10000000 -genome_coverage 0.1 -sample_number 1`

`#######################################`
`### REPEATMASKER to anotate contigs ###`
`#######################################`

`RepeatMasker version open-4.0.6`
`Search Engine: NCBI/RMBLAST [ 2.2.27+ ]`
`RepeatMasker could not find the repeat library at:`
`  ./bin/RepeatMasker/Libraries/RepeatMaskerLib.embl`
`This file is necessary to run RepeatMasker.  A minimal version of this`
`file is distributed with RepeatMasker.  For an extensive library of`
`interspersed repeats please obtain the complete file at:`
`http://www.girinst.org and install before using RepeatMasker.`

`Traceback (most recent call last):`
`  File "dnaPipeTE.py", line 700, in <module>`
`    RepeatMasker(config['DEFAULT']['RepeatMasker'], args.RepeatMasker_library,`
`args.RM_species, args.cpu, args.output_folder, args.RM_threshold)`
`  File "dnaPipeTE.py", line 359, in __init__`
`    self.repeatmasker_run()`
 ` File "dnaPipeTE.py", line 378, in repeatmasker_run`
`    with open(self.output_folder+"/Trinity.fasta.out", 'r') as trinity_handle:`
`IOError: [Errno 2] No such file or directory: 'test/Trinity.fasta.out'`

The test/test_dataset_example_output/ dir has two of the three output graphs: TEs_piechart and  bases_per_component

**Comment by clemgoub** [comment]
Hi Rahul and rotifergirl,

I'm reviewing the previous issues opened for previous version of dnaPipeTE since we migrate to version 1.3.
Did these issue has been solved for both of you?

Cheers,

Clément

**Comment by rotifergirl** [comment]
I'm no longer having this issue
