### ISSUE TITLE
forward vs reverse input file?

### ISSUE THREAD

**Issue by r-mashoodh** [clemgoub/dnaPipeTE#60]
Dear @clemgoub 

hi again! :)

I ran dnaPipeTE with the forward and the reverse and I got very different estimates of TE content. For ex. 34% with the Forward and 21% with the Reverse.

I checked the fastqc's and nothing very obviously different between F and R fastqs.

Is there any reason why this would happen? Should I be cleaning up the reads in some specific way? 

Thank you for all your help so far.

**Comment by clemgoub** [comment]
Hello r-mashoodh,

Ho that's interesting... I did not see that in my experience but I am interested to understand more about it. 
Can you give me all the details you have about your sequencing? Details about the library preparation and chemistry used for the sequencing.

I am going to perform test on my own to verify as well.

Best,

Clément

**Comment by r-mashoodh** [comment]
hi @clemgoub 

the library prep was NEB Next® Ultra™ DNA Library Prep Kit (Cat No. E7370L) using genomic DNA from some wild insect species (Qiagen DNEasy extraction). 

Would you like to know anything else?

I'm running the rest of the samples now as we speak!

cheers

**Comment by clemgoub** [comment]
Hi @r-mashoodh,

Ok, thanks. It is strange indeed. I would not expect it to be so different. Let me know how this goes with the other samples, and can you tell me what coverage you used? 

Does dnaPipeTE give you the piecharts? It would be interesting to know if the relative proportion of the different repeats classes are similar or different. For example, do F or R reads give you more NA than the other?

Cheers,

Clém
