### ISSUE TITLE
Trinity iteration issues with Singularity container

### ISSUE THREAD

**Issue by heidihyang** [clemgoub/dnaPipeTE#66]
Hi Clement,

I successfully installed the Singularity container of dnaPipeTE on my cluster after having some issues with my previous installation, but I keep getting Trinity issues. In particular I'm getting this error:
`awk: cannot open /global/scratch/users/heidihyang/001_tetragnathaTE/02_dnaPipeTE_outputs/test_001_output/Trinity_run0/chrysalis/readsToComponents.out.sort (No such file or directory)
Must specify basic parameters:  ex. Trinity --seqType fq --single reads.fq --max_memory 10G  at /opt/dnaPipeTE/bin/trinityrnaseq-Trinity-v2.5.1/Trinity line 853.
awk: cannot open /global/scratch/users/heidihyang/001_tetragnathaTE/02_dnaPipeTE_outputs/test_001_output/Trinity_run1/chrysalis/readsToComponents.out.sort (No such file or directory)
Must specify basic parameters:  ex. Trinity --seqType fq --single reads.fq --max_memory 10G  at /opt/dnaPipeTE/bin/trinityrnaseq-Trinity-v2.5.1/Trinity line 853.
sed: can't read /global/scratch/users/heidihyang/001_tetragnathaTE/02_dnaPipeTE_outputs/test_001_output/Trinity_run2/Trinity.fasta: No such file or directory
awk: cannot open /global/scratch/users/heidihyang/001_tetragnathaTE/02_dnaPipeTE_outputs/test_001_output/Trinity_run2/Trinity.fasta (No such file or directory)
/bin/sh: 1: -pa: not found`

I've attached my log below.
[001_test2_log.pdf](https://github.com/clemgoub/dnaPipeTE/files/8544131/001_test2_log.pdf)

Also this is the command I ran: `singularity exec /global/scratch/users/heidihyang/sing_DPTE/dnapipete.img python3 /opt/dnaPipeTE/dnaPipeTE.py -input /global/scratch/users/heidihyang/001_tetragnathaTE/01_data_from_jose/001_F.fastq.gz -output /global/scratch/users/heidihyang/001_tetragnathaTE/02_dnaPipeTE_outputs/test_001_output/ -RM_lib /global/scratch/users/heidihyang/001_tetragnathaTE/repeat_libs/repeatlib.fa -cpu 5 -genome_size 1100000000 -genome_coverage 0.25 -sample_number 2 -RM_t 0.2
`

Any ideas as to how I can resolve this issue? Thanks in advance!

Best,
Heidi

**Comment by clemgoub** [comment]
Hello Heidi,

I think you should try to run it in two steps. Let's say your local directory containing your reads is `/global/scratch/users/heidihyang/001_tetragnathaTE`

1. Create a command file `command.sh` in `/global/scratch/users/heidihyang/001_tetragnathaTE` file that will include:
```sh
#! /bin/bash
cd /opt/dnaPipeTE
python3 dnaPipeTE.py -input /mnt/01_data_from_jose/001_F.fastq.gz -output /mnt/test_001_output/ -RM_lib /mnt/001_tetragnathaTE/repeat_libs/repeatlib.fa -cpu 5 -genome_size 1100000000 -genome_coverage 0.25 -sample_number 2 -RM_t 0.2
```
>`/mnt` is the directory in the container where your local directory will be mounted. It will be equivalent to `/global/scratch/users/heidihyang/001_tetragnathaTE`

2. Use a generic command to launch the singularity container, binds the input/output folder and execute the aforementioned command file.
```sh
singularity exec --bind /global/scratch/users/heidihyang/001_tetragnathaTE:/mnt /global/scratch/users/heidihyang/sing_DPTE/dnapipete.img /mnt/command.sh
``` 

Let me know how it goes!

Cheers,

Clément

**Comment by heidihyang** [comment]
Hi Clément,

Thanks for the quick response! I get a FATAL: permission denied error when
I try to run the singularity exec code. I worked around this with my
cluster IT people using the code I was using earlier, and they were unsure
why it was throwing that "permission denied" error. However, when I did use
that workaround I got the Trinity errors. Are there any other workarounds
that might work in this case?

Best,
Heidi

**Comment by clemgoub** [comment]
Hello Heidi!

To confirm, you have the "permission denied" issue when you try to run 

```
singularity exec --bind /global/scratch/users/heidihyang/001_tetragnathaTE:/mnt /global/scratch/users/heidihyang/sing_DPTE/dnapipete.img /mnt/command.sh
```

If, yes, it may be that `command.sh` is not executable, you can try to `chmod+x command.sh` before launching the singularity exec command.

If it doesn't work, and you want to try with the code you used earlier, you will need to change the paths for the files in the dnaPipeTE command to reflect the mount point in the container. Thus, `/global/scratch/users/heidihyang/001_tetragnathaTE` needs to be replaced by `/mnt`, because these files will be accessible in the container in this folder (you indicate it to singularity with `--bind /global/scratch/users/heidihyang/001_tetragnathaTE:/mnt`). However, do not replace the path for the image (`/global/scratch/users/heidihyang/sing_DPTE/dnapipete.img`) as it is where singularity needs to go to find and run the image.

Let me know how it goes!

Cheers,

Clém

**Comment by clemgoub** [comment]
Please reopen if further assistance is needed! Best, Clément
