### ISSUE TITLE
FileNotFoundError: [Errno 2]

### ISSUE THREAD

**Issue by lablancoberdugo** [clemgoub/dnaPipeTE#69]
Hello Clemente, 
I am currently running danPipeTE and I am getting this error: 

#######################################
#######################################

Traceback (most recent call last):
  File "dnaPipeTE.py", line 698, in <module>
    RepeatMasker(config['DEFAULT']['RepeatMasker'], args.RepeatMasker_library, args.RM_species, args.cpu, args.output_folder, args.RM_threshold)
  File "dnaPipeTE.py", line 381, in __init__
    self.repeatmasker_run()
  File "dnaPipeTE.py", line 400, in repeatmasker_run
    with open(self.output_folder+"/Trinity.fasta.out", 'r') as trinity_handle:
FileNotFoundError: [Errno 2] No such file or directory: '/projects/dumont-lab/Laura/eQTL/dnapipe/data/Trinity.fasta.out'

####################
I am not super sure how to move forward

**Comment by clemgoub** [comment]
Hello Laura,

Can you send me the whole log as well as the commands you used? I seems that RepeatMasker did not work, but there could be several reasons. 

Do you have `Trinity.fasta` and does it have sequences within?

Thanks,

Clément

**Comment by lablancoberdugo** [comment]
Hey Clemente, 
tail of the log : 

***** TRINITY iteration 2 *****

Selecting reads for Trinity iteration number 2...
Done

Trinity iteration 2 Done'
renaming Trinity output...
done
/projects/dumont-lab/Laura/eQTL/dnapipe/data/Annotation/one_RM_hit_per_Trinity_contigs
/projects/dumont-lab/Laura/eQTL/dnapipe/data/Annotation/Best_RM_annot_80-80
/projects/dumont-lab/Laura/eQTL/dnapipe/data/Annotation/Best_RM_annot_partial
#######################################
### REPEATMASKER to anotate contigs ###
#######################################

Traceback (most recent call last):
  File "dnaPipeTE.py", line 698, in <module>
    RepeatMasker(config['DEFAULT']['RepeatMasker'], args.RepeatMasker_library, args.RM_species, args.cpu, args.output_folder, args.RM_threshold)
  File "dnaPipeTE.py", line 381, in __init__
    self.repeatmasker_run()
  File "dnaPipeTE.py", line 400, in repeatmasker_run
    with open(self.output_folder+"/Trinity.fasta.out", 'r') as trinity_handle:
FileNotFoundError: [Errno 2] No such file or directory: '/projects/dumont-lab/Laura/eQTL/dnapipe/data/Trinity.fasta.out'


command that I using: 

cd /projects/dumont-lab/Laura/eQTL/dnapipe
PERL5LIB=/home/blancl/anaconda3/envs/dnaPipeTE/lib/5.26.2/:$PERL5LIB

python3 dnaPipeTE.py -input /projects/dumont-lab/Laura/eQTL/dnapipe/data/14_R1.fastq.gz \
-output /projects/dumont-lab/Laura/eQTL/dnapipe/data \
-genome_size 180000000 \
-genome_coverage 0.15 \
-sample_number 2 \
-RM_lib ../RepeatMasker/Libraries/RepeatMasker.lib \
-RM_t 0.2 \
-cpu 8

**AND FOR THE Trinity.fa**

-rw-r--r-- 1 blancl dumont-lab       225189 Jun  1 15:08 Trinity.fasta

**Comment by lablancoberdugo** [comment]
[slurm-14764320.txt](https://github.com/clemgoub/dnaPipeTE/files/8818443/slurm-14764320.txt)

**Comment by clemgoub** [comment]
Hi Laura, just to confirm, you are not using the singularity version in this run right?

**Comment by lablancoberdugo** [comment]
oh no, I am sorry about the confusion. I am using the container. 

#############
# DNAPipeTE
#############
singularity exec \
--bind $DNAPIPETE $DNAPIPETE/dnapipete.img \
bash /projects/dumont-lab/Laura/eQTL/dnapipe/scripts/dnaPipeTE_cmd.sh

**Comment by clemgoub** [comment]
ok! so can you show me the file `dnaPipeTE_cmd.sh` ? thanks!

**Comment by lablancoberdugo** [comment]
Hello Clemente, 
Sorry for the late reply... I have been trouble shooting the software. I ended up using the non-container .py and running it till almost the end. 

I am getting what I believe is a blast error: 

**python3: can't open file '/projects/dumont-lab/Laura/eQTL/dnapipe/scripts/./blast_so
[config.ini.txt](https://github.com/clemgoub/dnaPipeTE/files/8838079/config.ini.txt)
[DNAPipeTE_script.sh.txt](https://github.com/clemgoub/dnaPipeTE/files/8838080/DNAPipeTE_script.sh.txt)
[slurm-14819468.out.txt](https://github.com/clemgoub/dnaPipeTE/files/8838081/slurm-14819468.out.txt)
rter.py': [Errno 2] No such file or directory**

this is not the path I gave it in the config file, so I am not sure how to fix that.
attached are the script file, the error and the config file.

**Comment by lablancoberdugo** [comment]
Hello Clemente,
Sorry for the late reply... I have been trouble shooting the software. I ended up using the non-container .py and running it till almost the end.

I am getting what I believe is a blast error:

python3: can't open file '/projects/dumont-lab/Laura/eQTL/dnapipe/scripts/./blast_sorter.py': [Errno 2] No such file or directory


this is not the path I gave it in the config file, so I am not sure how to fix that.
attached are the script file, the error and the config file.

[config.ini.txt](https://github.com/clemgoub/dnaPipeTE/files/8838084/config.ini.txt)
[DNAPipeTE_script.sh.txt](https://github.com/clemgoub/dnaPipeTE/files/8838085/DNAPipeTE_script.sh.txt)
[slurm-14819468.out.txt](https://github.com/clemgoub/dnaPipeTE/files/8838086/slurm-14819468.out.txt)

**Comment by lablancoberdugo** [comment]
Hello Clemete, 
I just checked the Trinity.fasta does have sequences in it ( 205058 Jun  4 00:16 Trinity.fasta). I will change the RAM and let it run again and I will report back in case we can set up a zoom meeting. 
I really appreciate the help!

**Comment by clemgoub** [comment]
Hello Laura! Please send me an email to ***@***.*** with your
availability so we set up a meeting =) It'll be easier!

**Comment by lablancoberdugo** [comment]
Clement for some reason your email was redacted. I went ahead and emailed the "contact" email from your website.
