### ISSUE TITLE
dnaPT_landscapes.sh running error

### ISSUE THREAD

**Issue by Liuxuanzeng** [clemgoub/dnaPipeTE#71]
$./dnaPT_landscapes.sh -I /home/liuxuanzeng/Project/0.3x/ -o /home/liuxuanzeng/dnaPipeTE/ -S
input dataset:      /home/liuxuanzeng/Project/0.3x/
output folder: /home/liuxuanzeng/dnaPipeTE/
output prefix: dnaPipeTE
super-family level: TRUE
custom ylim: FALSE
plotting Unknown: TRUE
[1] "load variables..."
Error in col.lands[i] <- cols$V2[grep(pattern = paste("^", levels(as.factor(land$TE_superfamily))[i], :
The length of the replacement parameter is zero
Stop the execution

I did a search, and maybe the error was running out of variable parameters.
I don't know what to do. Ask for help.
Thanks!

**Comment by clemgoub** [comment]
Dear @Liuxuanzeng, I have replied [here](https://github.com/clemgoub/dnaPT_utils/issues/1)
