### ISSUE TITLE
remove int.reads_vs_annoted.blast.out and repeat formatted libraries

### ISSUE THREAD

**Issue by mason-linscott** [clemgoub/dnaPipeTE#73]
Hi Clément,

I pulled the most recent version of dnaPipeTE wanted to report that the error in #55 still remains in the current singularity image and appears to prevent the intermediate blast3 outfiles and associated output pdfs from being generated. After manually correcting the image and rebuilding, the run completes and pdfs are generated.

I also had a suggestion to add a startup check to make sure any custom repeat library is formatted correctly (does not contain any repeat classes not able to be used by dnaPipeTE). When I ran the pipeline the first time using an EDTA library (contains polintons and various other classes) everything ran fine but I got a number of empty outfiles. I wasn't sure whether the error was #55 until I manually fixed the image and reran. This is mostly a fault on my end for not checking the allowed class list on the repo but I think it could help other users troubleshoot any issues.

Thank you for the wonderful tool and I wish you all the best,
Mason

**Comment by clemgoub** [comment]
Dear Mason, 

Thank you so much for your detailed investigation of the issue! If you're ok, I'd be down to upload your fixed image as an update and credit you as a contributor to dnaPipeTE on the github. Is it a singularity image or you also have the modified docker container? Either way, I can also update with your code. Let me know and I'll add your contribution!

Regarding your suggestion, it is a great idea, and indeed something I had in the back burner for a while now. I will up that on top of my to-do list (as well as keeping it in the list of objectives as we are working on dnaPipeTE 2). If you come up with something, I'll be once again happy to include your work as a contribution to the project. 

If you are interested, please contact me by email and we can set-up a meeting!

Cheers,

Clément
