### ISSUE TITLE
Could i use dnaPipeTE to annotate TE in small Eukaryotic genome ?

### ISSUE THREAD

**Issue by BenAawf** [clemgoub/dnaPipeTE#76]
Hi @clemgoub
Thank you for the amazing work. just by curiosity want to know if your tool is compatible with the whole genome, not raw reads. And is it recommended for TE annotation in small eukaryotic genomes?

BEST
ben

**Comment by clemgoub** [comment]
Hello Ben, thanks for your kind words!

dnaPipeTE is totally applicable to small eukaryotic genomes! I am very much looking forward for your feedback on these models.

You can also use dnaPipeTE starting from an assembled genome: you will first need to chop it off in small reads, which can be done with [ART](https://www.niehs.nih.gov/research/resources/software/biostatistics/art/index.cfm).

For your assembled genomes, you might also want to use de-novo TE search with for example [RepeatModeler2](https://www.repeatmasker.org/RepeatModeler/), [REPET](https://urgi.versailles.inra.fr/Tools/REPET) or [EDTA](https://github.com/oushujun/EDTA). These programs use an assembled genome as input and return a library of repeat consensus with basic classification (if found). Combining these with dnaPipeTE is also a possibility!

Let me know if you have further questions, I'll be happy to share experiences!

Cheers,

Clément
