### ISSUE TITLE
ERROR:main:Error reading file: This file cannot be read by this version of famdb.py.

### ISSUE THREAD

**Issue by AntonioBaeza** [clemgoub/dnaPipeTE#79]
To minimize frustration when attempting to make work the pipeline, I started attempting to construct the  library.fasta file.
I downloaded the Dfam.h5 file and the famdb.py script and there is this additional problem when attempting to create the library.fasta file. Any thought? I already opened an issue at the dfam github. Thanks

Singularity> ls
Dfam.h5 Dfam.h5.gz config.ini dnapipete.img famdb.py
Singularity>
Singularity> famdb.py -i Dfam.h5 families -f fasta_name -a Panarthropoda --include-class-in-name > library.fasta
ERROR:main:Error reading file: This file cannot be read by this version of famdb.py.
Singularity>

Any comment on how to proceed?
I tried the script with the last available Dfam database
thanks

**Comment by clemgoub** [comment]
Hi Antonio!

I suggest that you repeat the operation outside of the image (you'll need to clone `famdb` on your local machine). It is indeed possible that the version of `famdb.py` included in the package doesn't match a later version of DFAM. Technically, the image acts as a virtual machine, but it is not intended to store files (such as the library) anyways.

Let say you have on your local machine a directory called `~/Project`. In `~/Project`, you can create a directory called `data` that will host your input read as well as the TE library. If you follow [this tutorial](https://tehub.org/tutorials/docs/dnaPipeTE#h-31-start-the-container), when we start the image we mount the local directory `~/Project` as `mnt` in the image. You can see that the command [here](https://tehub.org/tutorials/docs/dnaPipeTE#h-32-run-dnapipete) calls the library with the prefix `/mnt/data`, which correspond to `~/Project/data`.

Let me know though if the issue persists while executing the command in your local machine. I will help with that.

Cheers, 

Clément

**Comment by AntonioBaeza** [comment]
I appreciate your input and help Clement.
Several issues. I tried the command after exiting singularity and did not work.
(base) ant@hillary:~/dnaPipeTE$ famdb.py -i Dfam.h5 families -f fasta_name -a Panarthropoda --include-class-in-name > library.fasta
famdb.py: command not found
Now, I was surprised by your recommendation to clone famdb. I went to the famdb github page, and it is indicated there that it is ok to use wget (for instance) to retrieve the script famdb.py, activate it, and then run it. I am not understanding something? thanks

**Comment by clemgoub** [comment]
Hello Antonio!

It seems that your local machine can't find the script. `wget` may work, but you might have downloaded it in another place than your current directory.

Try this:

1. Install `h5py`, which is a dependency for `famdb`

```
pip3 install --user h5py
```

2. Download `famdb.py` in a known location (for example, `~/`)

```
wget -O ~/famdb.py https://raw.githubusercontent.com/Dfam-consortium/FamDB/master/famdb.py 
chmod +x ~/famdb.py
```

3. Now, you should be able to run this command from any location:
```
~/famdb.py -i Dfam.h5 families -f fasta_name -a Panarthropoda --include-class-in-name > library.fasta
```

Let me know how it goes!

Cheers,

Clém

**Comment by AntonioBaeza** [comment]
Hi Clem. After some modifications, looks like the command is working. I am able to produce the library.fasta file but I was surprised that the final size is rather small. I thought it will be a heavy file with a collection of all rep. elements in the 'vertebrata' in my case, considering that TE are well studied in humans and mammals in general. Why such a small file then. Comments will be appreciated. Thanks for your help!

drwxrwxr-x  2 ant ant           49 Mar  6 20:17 ./
drwxr-xr-x 51 ant ant         4096 Mar  6 20:07 ../
-rw-r--r--  1 ant ant 779721628120 Mar  6 22:00 Dfam.h5
-rwxrwxr-x  1 ant ant        73352 Mar  6 20:10 famdb.py*
(base) ant@hillary:~/FAMDB$
(base) ant@hillary:~/FAMDB$
(base) ant@hillary:~/FAMDB$ famdb.py -i Dfam.h5 families -f fasta_name -a Vertebrata --include-class-in-name > library.fasta
famdb.py: command not found
(base) ant@hillary:~/FAMDB$ pwd
/home/ant/FAMDB
(base) ant@hillary:~/FAMDB$
(base) ant@hillary:~/FAMDB$ /home/ant/FAMDB/famdb.py -i Dfam.h5 families -f fasta_name -a Vertebrata --include-class-in-name > library.fasta
(base) ant@hillary:~/FAMDB$
(base) ant@hillary:~/FAMDB$ ls
Dfam.h5  famdb.py  library.fasta
(base) ant@hillary:~/FAMDB$
(base) ant@hillary:~/FAMDB$ head library.fasta
>5S#rRNA @Vertebrata_vertebrates [S:40,50]
GTCTACGGCCATACCACCCTGAACGCGCCCGATCTCGTCTGATCTCGGAAGCTAAGCAGG
GTCGGGCCTGGTTAGTACTTGGATGGGAGACCGCCTGGGAATACCGGGTGCTGTAGGCTT
T
>HY1#scRNA @Vertebrata_vertebrates [S:40,50]
GGCTGGTCCGAAGGTAGTGAGTTATCTCAATTGATTGTTCACAGTCAGTTACAGATCGAA
CTCCTTGTTCTACTCTTTCCCCCCTTCTCACTACTGCACTTGACTAGTCTTNAAAAAAA
>HY3#scRNA @Vertebrata_vertebrates [S:40,50]
GGCTGGTCCGAGTGCAGTGGTGTTTACAACTAATTGATCACAACCAGTTACAGATTTCTT
TGTTCCTTCTCCACTCCCACTGCTTCACTTGACTAGCCTTT
(base) ant@hillary:~/FAMDB$ ^C
(base) ant@hillary:~/FAMDB$
(base) ant@hillary:~/FAMDB$ ll
total 761447024
drwxrwxr-x  2 ant ant           74 Mar  6 22:12 ./
drwxr-xr-x 51 ant ant         4096 Mar  6 20:07 ../
-rw-r--r--  1 ant ant 779721628120 Mar  6 22:00 Dfam.h5
-rwxrwxr-x  1 ant ant        73352 Mar  6 20:10 famdb.py*
-rw-rw-r--  1 ant ant        38283 Mar  6 22:13 library.fasta
(base) ant@hillary:~/FAMDB$
(base) ant@hillary:~/FAMDB$

**Comment by clemgoub** [comment]
Hi Antonio!

Ho, I forgot something important! Depending the taxa you choose, you may want to add the ancestor (with `-a`) and/or descendant taxas (with `-d`). 

You can see [here](https://github.com/Dfam-consortium/FamDB#lineage) that `Vertebrata` has 79 entries, but the descendant nodes and leaves have much more (for example `Eutheria` has 462, and so on). Human, for example, has only 8 models, which are those that are specific TE of the human lineage. 

I can't test it right now, but will be happy to try later if this doesn't work.

Cheers,

Clément

**Comment by AntonioBaeza** [comment]
Hi Clemont. I am following the Tehub instructions and the help from famdb.py, still not able to get vertebratata and descendants. Trying several things, nothing working.

(base) ant@hillary:~/FAMDB$ pwd
/home/ant/FAMDB
(base) ant@hillary:~/FAMDB$ ll
total 761447024
drwxrwxr-x  2 ant ant           74 Mar  7 20:01 ./
drwxr-xr-x 51 ant ant         4096 Mar  6 20:07 ../
-rw-r--r--  1 ant ant 779721628120 Mar  6 22:00 Dfam.h5
-rwxrwxr-x  1 ant ant        73352 Mar  6 20:10 famdb.py*
-rw-rw-r--  1 ant ant        38283 Mar  6 22:13 library.fasta
(base) ant@hillary:~/FAMDB$
(base) ant@hillary:~/FAMDB$ /home/ant/FAMDB/famdb.py -i Dfam.h5 families -f fasta_name -a Vertebrata --include-class-in-name > library2.fasta
(base) ant@hillary:~/FAMDB$
(base) ant@hillary:~/FAMDB$ ll
total 761447064
drwxrwxr-x  2 ant ant          100 Mar  7 20:02 ./
drwxr-xr-x 51 ant ant         4096 Mar  6 20:07 ../
-rw-r--r--  1 ant ant 779721628120 Mar  6 22:00 Dfam.h5
-rwxrwxr-x  1 ant ant        73352 Mar  6 20:10 famdb.py*
-rw-rw-r--  1 ant ant        38283 Mar  7 20:02 library2.fasta  <<<<<< THIS IS WORKING AS BEFORE
-rw-rw-r--  1 ant ant        38283 Mar  6 22:13 library.fasta
(base) ant@hillary:~/FAMDB$
(base) ant@hillary:~/FAMDB$
(base) ant@hillary:~/FAMDB$ /home/ant/FAMDB/famdb.py -i Dfam.h5 families -d Theria -f fasta_name -a Vertebrata --include-class-in-name > library3.fasta
usage: famdb.py [-h] [-l LOG_LEVEL] [-i FILE]
                {info,names,lineage,families,family,append} ...
famdb.py: error: unrecognized arguments: Vertebrata
(base) ant@hillary:~/FAMDB$
(base) ant@hillary:~/FAMDB$ ll
total 761447064
drwxrwxr-x  2 ant ant          126 Mar  7 20:02 ./
drwxr-xr-x 51 ant ant         4096 Mar  6 20:07 ../
-rw-r--r--  1 ant ant 779721628120 Mar  6 22:00 Dfam.h5
-rwxrwxr-x  1 ant ant        73352 Mar  6 20:10 famdb.py*
-rw-rw-r--  1 ant ant        38283 Mar  7 20:02 library2.fasta
-rw-rw-r--  1 ant ant            0 Mar  7 20:02 library3.fasta
-rw-rw-r--  1 ant ant        38283 Mar  6 22:13 library.fasta
(base) ant@hillary:~/FAMDB$
(base) ant@hillary:~/FAMDB$ /home/ant/FAMDB/famdb.py -i Dfam.h5 families -d -f fasta_name -a Vertebrata --include-class-in-name > library4.fasta
^CTraceback (most recent call last):
  File "/home/ant/FAMDB/famdb.py", line 1914, in <module>
    main()
  File "/home/ant/FAMDB/famdb.py", line 1907, in main
    args.func(args)
  File "/home/ant/FAMDB/famdb.py", line 1680, in command_families
    accessions = sorted(args.file.get_accessions_filtered(tax_id=target_id,
  File "/home/ant/FAMDB/famdb.py", line 1334, in get_accessions_filtered
    for accession in iterate_accs():
  File "/home/ant/FAMDB/famdb.py", line 1331, in iterate_accs
    yield from self.get_families_for_taxon(node)
  File "/home/ant/miniconda3/lib/python3.8/_collections_abc.py", line 720, in __iter__
    yield from self._mapping
  File "/home/ant/.local/lib/python3.8/site-packages/h5py/_hl/group.py", line 499, in __iter__
    for x in self.id.__iter__():
KeyboardInterrupt

(base) ant@hillary:~/FAMDB$ ll
total 761447064
drwxrwxr-x  2 ant ant          152 Mar  7 20:02 ./
drwxr-xr-x 51 ant ant         4096 Mar  6 20:07 ../
-rw-r--r--  1 ant ant 779721628120 Mar  6 22:00 Dfam.h5
-rwxrwxr-x  1 ant ant        73352 Mar  6 20:10 famdb.py*
-rw-rw-r--  1 ant ant        38283 Mar  7 20:02 library2.fasta
-rw-rw-r--  1 ant ant            0 Mar  7 20:02 library3.fasta
-rw-rw-r--  1 ant ant            0 Mar  7 20:02 library4.fasta
-rw-rw-r--  1 ant ant        38283 Mar  6 22:13 library.fasta
(base) ant@hillary:~/FAMDB$
(base) ant@hillary:~/FAMDB$
(base) ant@hillary:~/FAMDB$ /home/ant/FAMDB/famdb.py -i Dfam.h5 lineage -d -f fasta_name -a Vertebrata --include-class-in-name > library5.fasta
usage: famdb.py lineage [-h] [-a] [-d] [-f <format>] term [term ...]
famdb.py lineage: error: argument -f/--format: invalid choice: 'fasta_name' (choose from 'pretty', 'semicolon', 'totals')
(base) ant@hillary:~/FAMDB$
(base) ant@hillary:~/FAMDB$ /home/ant/FAMDB/famdb.py -i Dfam.h5 lineage -d -f fasta_name Vertebrata --include-class-in-name > library6.fasta
usage: famdb.py lineage [-h] [-a] [-d] [-f <format>] term [term ...]
famdb.py lineage: error: argument -f/--format: invalid choice: 'fasta_name' (choose from 'pretty', 'semicolon', 'totals')
(base) ant@hillary:~/FAMDB$
(base) ant@hillary:~/FAMDB$
(base) ant@hillary:~/FAMDB$ /home/ant/FAMDB/famdb.py -h
usage: famdb.py [-h] [-l LOG_LEVEL] [-i FILE] {info,names,lineage,families,family,append} ...

This is famdb.py version 0.4.3.

example commands, including the most commonly used options:

  famdb.py [-i FILE] info
    Prints information about the file including database name and date.

  famdb.py [-i FILE] names 'mus' | head
    Prints taxonomy nodes that include 'mus', and the corresponding IDs.
    The IDs and names are stored in the FamDB file, and are based
    on the NCBI taxonomy database (https://www.ncbi.nlm.nih.gov/taxonomy).

  famdb.py [-i FILE] lineage -ad 'Homo sapiens'
  famdb.py [-i FILE] lineage -ad --format totals 9606
    Prints a taxonomic tree including the given clade and optionally ancestors
    and/or descendants, with the number of repeats indicated at each level of
    the hierarchy. With the 'totals' format, prints the number of matching
    ancestral and lineage-specific entries.

  famdb.py [-i FILE] family --format fasta_acc MIR3
    Exports a single family from the database in one of several formats.

  famdb.py [-i FILE] families -f embl_meta -ad --curated 'Drosophila melanogaster'
  famdb.py [-i FILE] families -f hmm -ad --curated --class LTR 7227
    Searches and exports multiple families from the database, in one of several formats.

optional arguments:
  -h, --help            show this help message and exit
  -l LOG_LEVEL, --log-level LOG_LEVEL
  -i FILE, --file FILE  specifies the file to query

subcommands:
  Specifies the kind of query to perform.
  For more information on all the possible options for a command, add the --help option after it:
  famdb.py families --help

  {info,names,lineage,families,family,append}
(base) ant@hillary:~/FAMDB$
(base) ant@hillary:~/FAMDB$ /home/ant/FAMDB/famdb.py -i Dfam.h5 families -f fasta_name -d Vertebrata --include-class-in-name > library2.fasta
^CTraceback (most recent call last):
  File "/home/ant/FAMDB/famdb.py", line 1914, in <module>
    main()
  File "/home/ant/FAMDB/famdb.py", line 1907, in main
    args.func(args)
  File "/home/ant/FAMDB/famdb.py", line 1680, in command_families
    accessions = sorted(args.file.get_accessions_filtered(tax_id=target_id,
  File "/home/ant/FAMDB/famdb.py", line 1334, in get_accessions_filtered
    for accession in iterate_accs():
  File "/home/ant/FAMDB/famdb.py", line 1331, in iterate_accs
    yield from self.get_families_for_taxon(node)
  File "/home/ant/miniconda3/lib/python3.8/_collections_abc.py", line 720, in __iter__
    yield from self._mapping
  File "/home/ant/.local/lib/python3.8/site-packages/h5py/_hl/group.py", line 499, in __iter__
    for x in self.id.__iter__():
KeyboardInterrupt

(base) ant@hillary:~/FAMDB$ ll
total 761447024
drwxrwxr-x  2 ant ant          204 Mar  7 20:14 ./
drwxr-xr-x 51 ant ant         4096 Mar  6 20:07 ../
-rw-r--r--  1 ant ant 779721628120 Mar  6 22:00 Dfam.h5
-rwxrwxr-x  1 ant ant        73352 Mar  6 20:10 famdb.py*
-rw-rw-r--  1 ant ant            0 Mar  7 20:21 library2.fasta
-rw-rw-r--  1 ant ant            0 Mar  7 20:02 library3.fasta
-rw-rw-r--  1 ant ant            0 Mar  7 20:02 library4.fasta
-rw-rw-r--  1 ant ant            0 Mar  7 20:13 library5.fasta
-rw-rw-r--  1 ant ant            0 Mar  7 20:14 library6.fasta
-rw-rw-r--  1 ant ant        38283 Mar  6 22:13 library.fasta
(base) ant@hillary:~/FAMDB$

Any option that I try fails! Thanks for your help.

**Comment by AntonioBaeza** [comment]
Just to let you know that is working. After trying several scripts the one below worked.
Surprised about the difference in the number of sequences when requesting descendants

(base) ant@hillary:~/FAMDB$ /home/ant/FAMDB/famdb.py -i Dfam.h5 families -f fasta_name -a -d Vertebrata --include-class-in-name > library14.fasta
(base) ant@hillary:~/FAMDB$ ll
total 763321316
drwxrwxr-x  2 ant ant         4096 Mar  7 21:04 ./
drwxr-xr-x 51 ant ant         4096 Mar  6 20:07 ../
-rw-r--r--  1 ant ant 779721628120 Mar  6 22:00 Dfam.h5
-rwxrwxr-x  1 ant ant        73352 Mar  6 20:10 famdb.py*
-rw-rw-r--  1 ant ant   1919226830 Mar  7 22:28 library14.fasta
-rw-rw-r--  1 ant ant        38283 Mar  6 22:13 library.fasta
(base) ant@hillary:~/FAMDB$

**Comment by clemgoub** [comment]
Hello Antonio,

Sorry the command line is a bit finicky! I'm glad you found the syntax that works for your use. I am editing your post so the code can be read easily and the answer found! 

Good analyses!

Clém

**Comment by clemgoub** [comment]
The number of descendant depends on the species-specificity of the families provided to DFAM. For a well explored group, with closely related species, such as human and primates, we can easily identify the shared TE between human and their common ancestors. In insects data, except maybe Drosophilas, the species sampling is more spread out, and many families are still species-specific due to a lack of closely related species.

You could see the number of expected families with:

```
famdb.py -i dfam.h5 lineage -ad Vertebrata
```
