### ISSUE TITLE
Trinity.fasta empty ~ java version

### ISSUE THREAD

**Issue by cslamo** [clemgoub/dnaPipeTE#8]
The program stops saying that Trinity.fasta (in the output folder) is empty (indeed 0 bytes). Way before this happens I get this message:

> Use of uninitialized value $java_version in pattern match (m//) at /home/manager/dnaPipeTE/bin/trinityrnaseq-Trinity-v2.5.1/Trinity line 1023.
> 
> 
> 
> ********************************************************************
> ** Warning, Trinity cannot determine which version of Java is being used.  Version 1.8 is required. 

I did run fixjava with an OK. This is my current version:

```
manager@sb:~/dnaPipeTE$ java -version
openjdk version "1.8.0_141-BLFS"
OpenJDK Runtime Environment (build 1.8.0_141-BLFS-b15)
OpenJDK 64-Bit Server VM (build 25.141-b15, mixed mode)
manager@sb:~/dnaPipeTE$ java -version
openjdk version "1.8.0_141-BLFS"
OpenJDK Runtime Environment (build 1.8.0_141-BLFS-b15)
OpenJDK 64-Bit Server VM (build 25.141-b15, mixed mode)
```
Will it fix by manually add the version in /dnaPipeTE/bin/trinityrnaseq-Trinity-v2.5.1/Trinity line 1023?

**Comment by clemgoub** [comment]
Hi cslamo,

The java warning might not be the reason of the why your Trinity.fasta is empty. Apparently, this could only be a warning.  It is possible that Trinity failed for another reason. When a wrong version of java is present, you have a different kind of error.

Could you post your whole log (including errors if you have them in a different file), as well as the command line you used?
Also, which configuration (server/cluster, single machine, OS) did you use?

Thanks a lot!

Clément

**Comment by cslamo** [comment]
Thanks. I'm running dnaPipeTE on Ubuntu 14.04LTS running on VM Virtualbox on a PC with 384G RAM and 2 8-core Xeon CPUs. I'm attaching the complete output screen for the run. 

The specified output folder (salidaTE) was created but it's empty

[dnaPipeTE1.txt](https://github.com/clemgoub/dnaPipeTE/files/1535746/dnaPipeTE1.txt)

**Comment by clemgoub** [comment]
Hi cslamo,

Indeed Java is not found in the path by when Trinity is executed, so this is well why it fails. 

If you start your VM, and run test_config.sh what is the result for the java test?
You can also directly do java --version at the start of the VM.

Since I assume you are administrator of the VM, you can directly try to install Java 8on Ubuntu, instead of using the version provided by Trinity.
```
sudo apt-get install openjdk-8-jdk
```

 If you do so, I recommend to remove from your ~/.bashrc the lines added by the fix_java.sh script:

```
### Add Java 8 from dnaPipeTE to Path
export JAVA_HOME=<yourpathtodnaPipeTE>/bin/OpenJDK-1.8.0.141-x86_64-bin
export PATH="$JAVA_HOME/bin:$PATH"
```

**Comment by cslamo** [comment]
Thanks. I installed java-8 

```
sudo add-apt-repository ppa:openjdk-r/ppa
sudo apt-get update
sudo apt-get install openjdk-8-jdk
``` 
and removed the bashrc entry as you said. Seems to be working now. 

Claudio

**Comment by clemgoub** [comment]
Awesome,

Let me know if you have further issues!

Best,

Clément
