### ISSUE TITLE
PERL Encode error when running DNApipeTE in Singularity

### ISSUE THREAD

**Issue by estolle** [clemgoub/dnaPipeTE#86]
Hi there

I am getting stuck in the Singularity/RM (image downloaded yesterday, Ubuntu 22.04) step due to a Perl error. I reinstalled the encode module but it still fails.

Any idea where this error comes from or how to fix it?

Thanks 
Eckart

#######################################
#######################################

Can't load '/home/ek/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/auto/Encode/Encode.so' for module Encode: /home/ek/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/auto/Encode/Encode.so: undefined symbol: PL_strict_utf8_dfa_tab at /usr/share/perl/5.24/XSLoader.pm line 96.
 at /home/ek/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/Encode.pm line 12.
BEGIN failed--compilation aborted at /home/ek/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/Encode.pm line 13.
Compilation failed in require at /usr/share/perl/5.24/Pod/Text.pm line 33.
BEGIN failed--compilation aborted at /usr/share/perl/5.24/Pod/Text.pm line 33.
Compilation failed in require at /opt/RepeatMasker/RepeatMasker line 320.
BEGIN failed--compilation aborted at /opt/RepeatMasker/RepeatMasker line 320.
Traceback (most recent call last):
  File "dnaPipeTE.py", line 698, in <module>
    RepeatMasker(config['DEFAULT']['RepeatMasker'], args.RepeatMasker_library, args.RM_species, args.cpu, args.output_folder, args.RM_threshold)       
  File "dnaPipeTE.py", line 381, in __init__
    self.repeatmasker_run()
  File "dnaPipeTE.py", line 400, in repeatmasker_run
    with open(self.output_folder+"/Trinity.fasta.out", 'r') as trinity_handle:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/Mflav.dnapipete.pass.shredded.output/Trinity.fasta.out'

**Comment by estolle** [comment]
I solved it. The problem was caused by adding additional perl folders to $PERL5LIB via my .bashrc. Once I remove them, it worked.

**Comment by clemgoub** [comment]
That the type of issue I like! Thanks for sharing the issue and the solution! Cheers!
