### ISSUE TITLE
Landscapes.R plot issue

### ISSUE THREAD

**Issue by rotifergirl** [clemgoub/dnaPipeTE#9]
Thanks for the new update! It runs very smoothly, I just found a problem with the landscapes.R plotting pipeline. The "factors_and_colors" file does not always have the correct amount of columns in each entry, so R does not open it. For example, the entry "DNA/Academ-1" does not have a class associated with it (in my file), so the second column is left open here. I made the plot manually after fixing the file, but thought you may like to be aware of it.

**Comment by clemgoub** [comment]
Hi rotifergirl,

Indeed, thanks for reporting the bug! I am fixing it right now and will update the repos ASAP!

Cheers,

Clém

**Comment by clemgoub** [comment]
It's updated, you can either pull from the git again or just only update the file "new_list_of_RM_superclass_colors_sortedOK"

**Comment by rotifergirl** [comment]
It's fixed and works perfectly now!

**Comment by clemgoub** [comment]
Awesome! Have fun!!
